// Code generated by ent, DO NOT EDIT.

package dictionaryexample

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the dictionaryexample type in the database.
	Label = "dictionary_example"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldTranslation holds the string denoting the translation field in the database.
	FieldTranslation = "translation"
	// FieldTargetPositionStart holds the string denoting the target_position_start field in the database.
	FieldTargetPositionStart = "target_position_start"
	// FieldTargetPositionEnd holds the string denoting the target_position_end field in the database.
	FieldTargetPositionEnd = "target_position_end"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDictionary holds the string denoting the dictionary edge name in mutations.
	EdgeDictionary = "dictionary"
	// Table holds the table name of the dictionaryexample in the database.
	Table = "dictionary_examples"
	// DictionaryTable is the table that holds the dictionary relation/edge.
	DictionaryTable = "dictionary_examples"
	// DictionaryInverseTable is the table name for the Dictionary entity.
	// It exists in this package in order to avoid circular dependency with the "dictionary" package.
	DictionaryInverseTable = "dictionaries"
	// DictionaryColumn is the table column denoting the dictionary relation/edge.
	DictionaryColumn = "dictionary_dictionary_examples"
)

// Columns holds all SQL columns for dictionaryexample fields.
var Columns = []string{
	FieldID,
	FieldText,
	FieldTranslation,
	FieldTargetPositionStart,
	FieldTargetPositionEnd,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "dictionary_examples"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"dictionary_dictionary_examples",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TargetPositionStartValidator is a validator for the "target_position_start" field. It is called by the builders before save.
	TargetPositionStartValidator func(int) error
	// TargetPositionEndValidator is a validator for the "target_position_end" field. It is called by the builders before save.
	TargetPositionEndValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the DictionaryExample queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByTranslation orders the results by the translation field.
func ByTranslation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTranslation, opts...).ToFunc()
}

// ByTargetPositionStart orders the results by the target_position_start field.
func ByTargetPositionStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetPositionStart, opts...).ToFunc()
}

// ByTargetPositionEnd orders the results by the target_position_end field.
func ByTargetPositionEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetPositionEnd, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDictionaryField orders the results by dictionary field.
func ByDictionaryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDictionaryStep(), sql.OrderByField(field, opts...))
	}
}
func newDictionaryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DictionaryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DictionaryTable, DictionaryColumn),
	)
}
