#!/bin/bash

echo "Pre-push hook: запуск тестов Go..."

# Запускаем тесты Go
go test -v ./...

if [ $? -ne 0 ]; then
    echo "Тесты не прошли. Пожалуйста, исправьте ошибки перед пушем."
    exit 1
else
    echo "Все тесты прошли успешно."
fi

exit 0