// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID           pgtype.UUID
	Title        string
	Author       string
	ChapterPaths []string
	Cover        pgtype.Text
}

type Dictionary struct {
	ID      pgtype.UUID
	Text    string
	Lang    string
	Content []byte
}

type EmailPasswordAccount struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
}

type FcmToken struct {
	Token    string
	UserID   pgtype.UUID
	CreateAt pgtype.Timestamptz
}

type GoogleAccount struct {
	Sub           string
	Email         string
	EmailVerified bool
	Name          string
	Picture       pgtype.Text
}

type User struct {
	ID                     pgtype.UUID
	IsAdmin                bool
	IsVip                  pgtype.Bool
	Metadata               []byte
	GoogleAccountSub       pgtype.Text
	EmailPasswordAccountID pgtype.UUID
}
