// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationSender creates a new instance of MockNotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationSender {
	mock := &MockNotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationSender is an autogenerated mock type for the NotificationSender type
type MockNotificationSender struct {
	mock.Mock
}

type MockNotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationSender) EXPECT() *MockNotificationSender_Expecter {
	return &MockNotificationSender_Expecter{mock: &_m.Mock}
}

// Emit provides a mock function for the type MockNotificationSender
func (_mock *MockNotificationSender) Emit(ctx context.Context, notification *domain.Notification) {
	_mock.Called(ctx, notification)
	return
}

// MockNotificationSender_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type MockNotificationSender_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - notification *domain.Notification
func (_e *MockNotificationSender_Expecter) Emit(ctx interface{}, notification interface{}) *MockNotificationSender_Emit_Call {
	return &MockNotificationSender_Emit_Call{Call: _e.mock.On("Emit", ctx, notification)}
}

func (_c *MockNotificationSender_Emit_Call) Run(run func(ctx context.Context, notification *domain.Notification)) *MockNotificationSender_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Notification
		if args[1] != nil {
			arg1 = args[1].(*domain.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationSender_Emit_Call) Return() *MockNotificationSender_Emit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotificationSender_Emit_Call) RunAndReturn(run func(ctx context.Context, notification *domain.Notification)) *MockNotificationSender_Emit_Call {
	_c.Run(run)
	return _c
}
