// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPersonalBookRepository creates a new instance of MockPersonalBookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPersonalBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPersonalBookRepository {
	mock := &MockPersonalBookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPersonalBookRepository is an autogenerated mock type for the PersonalBookRepository type
type MockPersonalBookRepository struct {
	mock.Mock
}

type MockPersonalBookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPersonalBookRepository) EXPECT() *MockPersonalBookRepository_Expecter {
	return &MockPersonalBookRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) Create(ctx context.Context, book *domain.PersonalBook) (*domain.PersonalBook, error) {
	ret := _mock.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.PersonalBook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBook) (*domain.PersonalBook, error)); ok {
		return returnFunc(ctx, book)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBook) *domain.PersonalBook); ok {
		r0 = returnFunc(ctx, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.PersonalBook) error); ok {
		r1 = returnFunc(ctx, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPersonalBookRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - book *domain.PersonalBook
func (_e *MockPersonalBookRepository_Expecter) Create(ctx interface{}, book interface{}) *MockPersonalBookRepository_Create_Call {
	return &MockPersonalBookRepository_Create_Call{Call: _e.mock.On("Create", ctx, book)}
}

func (_c *MockPersonalBookRepository_Create_Call) Run(run func(ctx context.Context, book *domain.PersonalBook)) *MockPersonalBookRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.PersonalBook
		if args[1] != nil {
			arg1 = args[1].(*domain.PersonalBook)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_Create_Call) Return(personalBook *domain.PersonalBook, err error) *MockPersonalBookRepository_Create_Call {
	_c.Call.Return(personalBook, err)
	return _c
}

func (_c *MockPersonalBookRepository_Create_Call) RunAndReturn(run func(ctx context.Context, book *domain.PersonalBook) (*domain.PersonalBook, error)) *MockPersonalBookRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChapter provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) CreateChapter(ctx context.Context, chapter *domain.PersonalBookChapter) (*domain.PersonalBookChapter, error) {
	ret := _mock.Called(ctx, chapter)

	if len(ret) == 0 {
		panic("no return value specified for CreateChapter")
	}

	var r0 *domain.PersonalBookChapter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBookChapter) (*domain.PersonalBookChapter, error)); ok {
		return returnFunc(ctx, chapter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBookChapter) *domain.PersonalBookChapter); ok {
		r0 = returnFunc(ctx, chapter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBookChapter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.PersonalBookChapter) error); ok {
		r1 = returnFunc(ctx, chapter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_CreateChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChapter'
type MockPersonalBookRepository_CreateChapter_Call struct {
	*mock.Call
}

// CreateChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - chapter *domain.PersonalBookChapter
func (_e *MockPersonalBookRepository_Expecter) CreateChapter(ctx interface{}, chapter interface{}) *MockPersonalBookRepository_CreateChapter_Call {
	return &MockPersonalBookRepository_CreateChapter_Call{Call: _e.mock.On("CreateChapter", ctx, chapter)}
}

func (_c *MockPersonalBookRepository_CreateChapter_Call) Run(run func(ctx context.Context, chapter *domain.PersonalBookChapter)) *MockPersonalBookRepository_CreateChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.PersonalBookChapter
		if args[1] != nil {
			arg1 = args[1].(*domain.PersonalBookChapter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_CreateChapter_Call) Return(personalBookChapter *domain.PersonalBookChapter, err error) *MockPersonalBookRepository_CreateChapter_Call {
	_c.Call.Return(personalBookChapter, err)
	return _c
}

func (_c *MockPersonalBookRepository_CreateChapter_Call) RunAndReturn(run func(ctx context.Context, chapter *domain.PersonalBookChapter) (*domain.PersonalBookChapter, error)) *MockPersonalBookRepository_CreateChapter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndAuthorAndTitle provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) GetByUserAndAuthorAndTitle(ctx context.Context, userID domain.ID, authorName string, title string) (*domain.PersonalBook, error) {
	ret := _mock.Called(ctx, userID, authorName, title)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndAuthorAndTitle")
	}

	var r0 *domain.PersonalBook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, string, string) (*domain.PersonalBook, error)); ok {
		return returnFunc(ctx, userID, authorName, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, string, string) *domain.PersonalBook); ok {
		r0 = returnFunc(ctx, userID, authorName, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID, string, string) error); ok {
		r1 = returnFunc(ctx, userID, authorName, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndAuthorAndTitle'
type MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call struct {
	*mock.Call
}

// GetByUserAndAuthorAndTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.ID
//   - authorName string
//   - title string
func (_e *MockPersonalBookRepository_Expecter) GetByUserAndAuthorAndTitle(ctx interface{}, userID interface{}, authorName interface{}, title interface{}) *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call {
	return &MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call{Call: _e.mock.On("GetByUserAndAuthorAndTitle", ctx, userID, authorName, title)}
}

func (_c *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call) Run(run func(ctx context.Context, userID domain.ID, authorName string, title string)) *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call) Return(personalBook *domain.PersonalBook, err error) *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call {
	_c.Call.Return(personalBook, err)
	return _c
}

func (_c *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call) RunAndReturn(run func(ctx context.Context, userID domain.ID, authorName string, title string) (*domain.PersonalBook, error)) *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call {
	_c.Call.Return(run)
	return _c
}

// GetChapterByPersonalBookIDAndOrder provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) GetChapterByPersonalBookIDAndOrder(ctx context.Context, personalBookID domain.ID, orderChapter int) (*domain.PersonalBookChapter, error) {
	ret := _mock.Called(ctx, personalBookID, orderChapter)

	if len(ret) == 0 {
		panic("no return value specified for GetChapterByPersonalBookIDAndOrder")
	}

	var r0 *domain.PersonalBookChapter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, int) (*domain.PersonalBookChapter, error)); ok {
		return returnFunc(ctx, personalBookID, orderChapter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, int) *domain.PersonalBookChapter); ok {
		r0 = returnFunc(ctx, personalBookID, orderChapter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBookChapter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID, int) error); ok {
		r1 = returnFunc(ctx, personalBookID, orderChapter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChapterByPersonalBookIDAndOrder'
type MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call struct {
	*mock.Call
}

// GetChapterByPersonalBookIDAndOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - personalBookID domain.ID
//   - orderChapter int
func (_e *MockPersonalBookRepository_Expecter) GetChapterByPersonalBookIDAndOrder(ctx interface{}, personalBookID interface{}, orderChapter interface{}) *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call {
	return &MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call{Call: _e.mock.On("GetChapterByPersonalBookIDAndOrder", ctx, personalBookID, orderChapter)}
}

func (_c *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call) Run(run func(ctx context.Context, personalBookID domain.ID, orderChapter int)) *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call) Return(personalBookChapter *domain.PersonalBookChapter, err error) *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call {
	_c.Call.Return(personalBookChapter, err)
	return _c
}

func (_c *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call) RunAndReturn(run func(ctx context.Context, personalBookID domain.ID, orderChapter int) (*domain.PersonalBookChapter, error)) *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call {
	_c.Call.Return(run)
	return _c
}
