dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase }}.go"
structname: "Mock{{.InterfaceName}}"
pkgname: "mocks"

packages:
  github.com/nimyab/nim2book-back/internal/repository:
    config:
      all: true
  github.com/nimyab/nim2book-back/internal/services:
    config:
      recursive: true
      all: true
