// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package translate_personal_user_book

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	"github.com/nimyab/nim2book-back/internal/services/libretranslate/translate"
	"github.com/nimyab/nim2book-back/proto/word_aligner"
	mock "github.com/stretchr/testify/mock"
)

// NewMockS3 creates a new instance of MockS3. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3 {
	mock := &MockS3{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3 is an autogenerated mock type for the S3 type
type MockS3 struct {
	mock.Mock
}

type MockS3_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3) EXPECT() *MockS3_Expecter {
	return &MockS3_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockS3
func (_mock *MockS3) Check(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockS3_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - path string
func (_e *MockS3_Expecter) Check(path interface{}) *MockS3_Check_Call {
	return &MockS3_Check_Call{Call: _e.mock.On("Check", path)}
}

func (_c *MockS3_Check_Call) Run(run func(path string)) *MockS3_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockS3_Check_Call) Return(err error) *MockS3_Check_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3_Check_Call) RunAndReturn(run func(path string) error) *MockS3_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockS3
func (_mock *MockS3) Upload(path string, data []byte) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockS3_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - path string
//   - data []byte
func (_e *MockS3_Expecter) Upload(path interface{}, data interface{}) *MockS3_Upload_Call {
	return &MockS3_Upload_Call{Call: _e.mock.On("Upload", path, data)}
}

func (_c *MockS3_Upload_Call) Run(run func(path string, data []byte)) *MockS3_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3_Upload_Call) Return(err error) *MockS3_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3_Upload_Call) RunAndReturn(run func(path string, data []byte) error) *MockS3_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPersonalBookRepository creates a new instance of MockPersonalBookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPersonalBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPersonalBookRepository {
	mock := &MockPersonalBookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPersonalBookRepository is an autogenerated mock type for the PersonalBookRepository type
type MockPersonalBookRepository struct {
	mock.Mock
}

type MockPersonalBookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPersonalBookRepository) EXPECT() *MockPersonalBookRepository_Expecter {
	return &MockPersonalBookRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) Create(ctx context.Context, book *domain.PersonalBook) (*domain.PersonalBook, error) {
	ret := _mock.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.PersonalBook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBook) (*domain.PersonalBook, error)); ok {
		return returnFunc(ctx, book)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBook) *domain.PersonalBook); ok {
		r0 = returnFunc(ctx, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.PersonalBook) error); ok {
		r1 = returnFunc(ctx, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPersonalBookRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - book *domain.PersonalBook
func (_e *MockPersonalBookRepository_Expecter) Create(ctx interface{}, book interface{}) *MockPersonalBookRepository_Create_Call {
	return &MockPersonalBookRepository_Create_Call{Call: _e.mock.On("Create", ctx, book)}
}

func (_c *MockPersonalBookRepository_Create_Call) Run(run func(ctx context.Context, book *domain.PersonalBook)) *MockPersonalBookRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.PersonalBook
		if args[1] != nil {
			arg1 = args[1].(*domain.PersonalBook)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_Create_Call) Return(personalBook *domain.PersonalBook, err error) *MockPersonalBookRepository_Create_Call {
	_c.Call.Return(personalBook, err)
	return _c
}

func (_c *MockPersonalBookRepository_Create_Call) RunAndReturn(run func(ctx context.Context, book *domain.PersonalBook) (*domain.PersonalBook, error)) *MockPersonalBookRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChapter provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) CreateChapter(ctx context.Context, chapter *domain.PersonalBookChapter) (*domain.PersonalBookChapter, error) {
	ret := _mock.Called(ctx, chapter)

	if len(ret) == 0 {
		panic("no return value specified for CreateChapter")
	}

	var r0 *domain.PersonalBookChapter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBookChapter) (*domain.PersonalBookChapter, error)); ok {
		return returnFunc(ctx, chapter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBookChapter) *domain.PersonalBookChapter); ok {
		r0 = returnFunc(ctx, chapter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBookChapter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.PersonalBookChapter) error); ok {
		r1 = returnFunc(ctx, chapter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_CreateChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChapter'
type MockPersonalBookRepository_CreateChapter_Call struct {
	*mock.Call
}

// CreateChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - chapter *domain.PersonalBookChapter
func (_e *MockPersonalBookRepository_Expecter) CreateChapter(ctx interface{}, chapter interface{}) *MockPersonalBookRepository_CreateChapter_Call {
	return &MockPersonalBookRepository_CreateChapter_Call{Call: _e.mock.On("CreateChapter", ctx, chapter)}
}

func (_c *MockPersonalBookRepository_CreateChapter_Call) Run(run func(ctx context.Context, chapter *domain.PersonalBookChapter)) *MockPersonalBookRepository_CreateChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.PersonalBookChapter
		if args[1] != nil {
			arg1 = args[1].(*domain.PersonalBookChapter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_CreateChapter_Call) Return(personalBookChapter *domain.PersonalBookChapter, err error) *MockPersonalBookRepository_CreateChapter_Call {
	_c.Call.Return(personalBookChapter, err)
	return _c
}

func (_c *MockPersonalBookRepository_CreateChapter_Call) RunAndReturn(run func(ctx context.Context, chapter *domain.PersonalBookChapter) (*domain.PersonalBookChapter, error)) *MockPersonalBookRepository_CreateChapter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndAuthorAndTitle provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) GetByUserAndAuthorAndTitle(ctx context.Context, userID domain.ID, authorName string, title string) (*domain.PersonalBook, error) {
	ret := _mock.Called(ctx, userID, authorName, title)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndAuthorAndTitle")
	}

	var r0 *domain.PersonalBook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, string, string) (*domain.PersonalBook, error)); ok {
		return returnFunc(ctx, userID, authorName, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, string, string) *domain.PersonalBook); ok {
		r0 = returnFunc(ctx, userID, authorName, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID, string, string) error); ok {
		r1 = returnFunc(ctx, userID, authorName, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndAuthorAndTitle'
type MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call struct {
	*mock.Call
}

// GetByUserAndAuthorAndTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.ID
//   - authorName string
//   - title string
func (_e *MockPersonalBookRepository_Expecter) GetByUserAndAuthorAndTitle(ctx interface{}, userID interface{}, authorName interface{}, title interface{}) *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call {
	return &MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call{Call: _e.mock.On("GetByUserAndAuthorAndTitle", ctx, userID, authorName, title)}
}

func (_c *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call) Run(run func(ctx context.Context, userID domain.ID, authorName string, title string)) *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call) Return(personalBook *domain.PersonalBook, err error) *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call {
	_c.Call.Return(personalBook, err)
	return _c
}

func (_c *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call) RunAndReturn(run func(ctx context.Context, userID domain.ID, authorName string, title string) (*domain.PersonalBook, error)) *MockPersonalBookRepository_GetByUserAndAuthorAndTitle_Call {
	_c.Call.Return(run)
	return _c
}

// GetChapterByPersonalBookIDAndOrder provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) GetChapterByPersonalBookIDAndOrder(ctx context.Context, personalBookID domain.ID, orderChapter int) (*domain.PersonalBookChapter, error) {
	ret := _mock.Called(ctx, personalBookID, orderChapter)

	if len(ret) == 0 {
		panic("no return value specified for GetChapterByPersonalBookIDAndOrder")
	}

	var r0 *domain.PersonalBookChapter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, int) (*domain.PersonalBookChapter, error)); ok {
		return returnFunc(ctx, personalBookID, orderChapter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, int) *domain.PersonalBookChapter); ok {
		r0 = returnFunc(ctx, personalBookID, orderChapter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBookChapter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID, int) error); ok {
		r1 = returnFunc(ctx, personalBookID, orderChapter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChapterByPersonalBookIDAndOrder'
type MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call struct {
	*mock.Call
}

// GetChapterByPersonalBookIDAndOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - personalBookID domain.ID
//   - orderChapter int
func (_e *MockPersonalBookRepository_Expecter) GetChapterByPersonalBookIDAndOrder(ctx interface{}, personalBookID interface{}, orderChapter interface{}) *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call {
	return &MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call{Call: _e.mock.On("GetChapterByPersonalBookIDAndOrder", ctx, personalBookID, orderChapter)}
}

func (_c *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call) Run(run func(ctx context.Context, personalBookID domain.ID, orderChapter int)) *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call) Return(personalBookChapter *domain.PersonalBookChapter, err error) *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call {
	_c.Call.Return(personalBookChapter, err)
	return _c
}

func (_c *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call) RunAndReturn(run func(ctx context.Context, personalBookID domain.ID, orderChapter int) (*domain.PersonalBookChapter, error)) *MockPersonalBookRepository_GetChapterByPersonalBookIDAndOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcessStatus provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) UpdateProcessStatus(ctx context.Context, id domain.ID, processStatus domain.ProcessStatus) (*domain.PersonalBook, error) {
	ret := _mock.Called(ctx, id, processStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcessStatus")
	}

	var r0 *domain.PersonalBook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, domain.ProcessStatus) (*domain.PersonalBook, error)); ok {
		return returnFunc(ctx, id, processStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, domain.ProcessStatus) *domain.PersonalBook); ok {
		r0 = returnFunc(ctx, id, processStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID, domain.ProcessStatus) error); ok {
		r1 = returnFunc(ctx, id, processStatus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_UpdateProcessStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcessStatus'
type MockPersonalBookRepository_UpdateProcessStatus_Call struct {
	*mock.Call
}

// UpdateProcessStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
//   - processStatus domain.ProcessStatus
func (_e *MockPersonalBookRepository_Expecter) UpdateProcessStatus(ctx interface{}, id interface{}, processStatus interface{}) *MockPersonalBookRepository_UpdateProcessStatus_Call {
	return &MockPersonalBookRepository_UpdateProcessStatus_Call{Call: _e.mock.On("UpdateProcessStatus", ctx, id, processStatus)}
}

func (_c *MockPersonalBookRepository_UpdateProcessStatus_Call) Run(run func(ctx context.Context, id domain.ID, processStatus domain.ProcessStatus)) *MockPersonalBookRepository_UpdateProcessStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		var arg2 domain.ProcessStatus
		if args[2] != nil {
			arg2 = args[2].(domain.ProcessStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_UpdateProcessStatus_Call) Return(personalBook *domain.PersonalBook, err error) *MockPersonalBookRepository_UpdateProcessStatus_Call {
	_c.Call.Return(personalBook, err)
	return _c
}

func (_c *MockPersonalBookRepository_UpdateProcessStatus_Call) RunAndReturn(run func(ctx context.Context, id domain.ID, processStatus domain.ProcessStatus) (*domain.PersonalBook, error)) *MockPersonalBookRepository_UpdateProcessStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorRepository creates a new instance of MockAuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorRepository {
	mock := &MockAuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorRepository is an autogenerated mock type for the AuthorRepository type
type MockAuthorRepository struct {
	mock.Mock
}

type MockAuthorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorRepository) EXPECT() *MockAuthorRepository_Expecter {
	return &MockAuthorRepository_Expecter{mock: &_m.Mock}
}

// GetOrCreate provides a mock function for the type MockAuthorRepository
func (_mock *MockAuthorRepository) GetOrCreate(ctx context.Context, name string) (*domain.Author, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *domain.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Author, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Author); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthorRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockAuthorRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAuthorRepository_Expecter) GetOrCreate(ctx interface{}, name interface{}) *MockAuthorRepository_GetOrCreate_Call {
	return &MockAuthorRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, name)}
}

func (_c *MockAuthorRepository_GetOrCreate_Call) Run(run func(ctx context.Context, name string)) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorRepository_GetOrCreate_Call) Return(author *domain.Author, err error) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockAuthorRepository_GetOrCreate_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.Author, error)) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWordAligner creates a new instance of MockWordAligner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWordAligner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWordAligner {
	mock := &MockWordAligner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWordAligner is an autogenerated mock type for the WordAligner type
type MockWordAligner struct {
	mock.Mock
}

type MockWordAligner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWordAligner) EXPECT() *MockWordAligner_Expecter {
	return &MockWordAligner_Expecter{mock: &_m.Mock}
}

// Align provides a mock function for the type MockWordAligner
func (_mock *MockWordAligner) Align(ctx context.Context, req *word_aligner.AlignRequest) (*word_aligner.AlignResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Align")
	}

	var r0 *word_aligner.AlignResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *word_aligner.AlignRequest) (*word_aligner.AlignResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *word_aligner.AlignRequest) *word_aligner.AlignResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*word_aligner.AlignResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *word_aligner.AlignRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordAligner_Align_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Align'
type MockWordAligner_Align_Call struct {
	*mock.Call
}

// Align is a helper method to define mock.On call
//   - ctx context.Context
//   - req *word_aligner.AlignRequest
func (_e *MockWordAligner_Expecter) Align(ctx interface{}, req interface{}) *MockWordAligner_Align_Call {
	return &MockWordAligner_Align_Call{Call: _e.mock.On("Align", ctx, req)}
}

func (_c *MockWordAligner_Align_Call) Run(run func(ctx context.Context, req *word_aligner.AlignRequest)) *MockWordAligner_Align_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *word_aligner.AlignRequest
		if args[1] != nil {
			arg1 = args[1].(*word_aligner.AlignRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWordAligner_Align_Call) Return(alignResponse *word_aligner.AlignResponse, err error) *MockWordAligner_Align_Call {
	_c.Call.Return(alignResponse, err)
	return _c
}

func (_c *MockWordAligner_Align_Call) RunAndReturn(run func(ctx context.Context, req *word_aligner.AlignRequest) (*word_aligner.AlignResponse, error)) *MockWordAligner_Align_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTranslator creates a new instance of MockTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslator {
	mock := &MockTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranslator is an autogenerated mock type for the Translator type
type MockTranslator struct {
	mock.Mock
}

type MockTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslator) EXPECT() *MockTranslator_Expecter {
	return &MockTranslator_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function for the type MockTranslator
func (_mock *MockTranslator) Translate(input *translate.Input) (*translate.Output, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 *translate.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*translate.Input) (*translate.Output, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(*translate.Input) *translate.Output); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*translate.Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*translate.Input) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranslator_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockTranslator_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - input *translate.Input
func (_e *MockTranslator_Expecter) Translate(input interface{}) *MockTranslator_Translate_Call {
	return &MockTranslator_Translate_Call{Call: _e.mock.On("Translate", input)}
}

func (_c *MockTranslator_Translate_Call) Run(run func(input *translate.Input)) *MockTranslator_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *translate.Input
		if args[0] != nil {
			arg0 = args[0].(*translate.Input)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranslator_Translate_Call) Return(output *translate.Output, err error) *MockTranslator_Translate_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockTranslator_Translate_Call) RunAndReturn(run func(input *translate.Input) (*translate.Output, error)) *MockTranslator_Translate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationSender creates a new instance of MockNotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationSender {
	mock := &MockNotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationSender is an autogenerated mock type for the NotificationSender type
type MockNotificationSender struct {
	mock.Mock
}

type MockNotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationSender) EXPECT() *MockNotificationSender_Expecter {
	return &MockNotificationSender_Expecter{mock: &_m.Mock}
}

// Emit provides a mock function for the type MockNotificationSender
func (_mock *MockNotificationSender) Emit(ctx context.Context, notification *domain.Notification) {
	_mock.Called(ctx, notification)
	return
}

// MockNotificationSender_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type MockNotificationSender_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - notification *domain.Notification
func (_e *MockNotificationSender_Expecter) Emit(ctx interface{}, notification interface{}) *MockNotificationSender_Emit_Call {
	return &MockNotificationSender_Emit_Call{Call: _e.mock.On("Emit", ctx, notification)}
}

func (_c *MockNotificationSender_Emit_Call) Run(run func(ctx context.Context, notification *domain.Notification)) *MockNotificationSender_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Notification
		if args[1] != nil {
			arg1 = args[1].(*domain.Notification)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNotificationSender_Emit_Call) Return() *MockNotificationSender_Emit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotificationSender_Emit_Call) RunAndReturn(run func(ctx context.Context, notification *domain.Notification)) *MockNotificationSender_Emit_Call {
	_c.Run(run)
	return _c
}
