// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenreRepository creates a new instance of MockGenreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenreRepository {
	mock := &MockGenreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenreRepository is an autogenerated mock type for the GenreRepository type
type MockGenreRepository struct {
	mock.Mock
}

type MockGenreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenreRepository) EXPECT() *MockGenreRepository_Expecter {
	return &MockGenreRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockGenreRepository
func (_mock *MockGenreRepository) GetByID(ctx context.Context, id domain.ID) (*domain.Genre, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Genre
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.Genre, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.Genre); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Genre)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenreRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGenreRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockGenreRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockGenreRepository_GetByID_Call {
	return &MockGenreRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockGenreRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockGenreRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenreRepository_GetByID_Call) Return(genre *domain.Genre, err error) *MockGenreRepository_GetByID_Call {
	_c.Call.Return(genre, err)
	return _c
}

func (_c *MockGenreRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.Genre, error)) *MockGenreRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
