// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookRepository creates a new instance of MockBookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookRepository {
	mock := &MockBookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookRepository is an autogenerated mock type for the BookRepository type
type MockBookRepository struct {
	mock.Mock
}

type MockBookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookRepository) EXPECT() *MockBookRepository_Expecter {
	return &MockBookRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockBookRepository
func (_mock *MockBookRepository) GetByID(ctx context.Context, id domain.ID) (*domain.Book, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.Book, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.Book); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBookRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockBookRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockBookRepository_GetByID_Call {
	return &MockBookRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockBookRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockBookRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookRepository_GetByID_Call) Return(book *domain.Book, err error) *MockBookRepository_GetByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockBookRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.Book, error)) *MockBookRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBookRepository
func (_mock *MockBookRepository) Update(ctx context.Context, book *domain.Book) (*domain.Book, error) {
	ret := _mock.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Book) (*domain.Book, error)); ok {
		return returnFunc(ctx, book)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Book) *domain.Book); ok {
		r0 = returnFunc(ctx, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Book) error); ok {
		r1 = returnFunc(ctx, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBookRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - book *domain.Book
func (_e *MockBookRepository_Expecter) Update(ctx interface{}, book interface{}) *MockBookRepository_Update_Call {
	return &MockBookRepository_Update_Call{Call: _e.mock.On("Update", ctx, book)}
}

func (_c *MockBookRepository_Update_Call) Run(run func(ctx context.Context, book *domain.Book)) *MockBookRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Book
		if args[1] != nil {
			arg1 = args[1].(*domain.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookRepository_Update_Call) Return(book1 *domain.Book, err error) *MockBookRepository_Update_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockBookRepository_Update_Call) RunAndReturn(run func(ctx context.Context, book *domain.Book) (*domain.Book, error)) *MockBookRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
