// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package translate_book

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	"github.com/nimyab/nim2book-back/internal/services/libretranslate/translate"
	"github.com/nimyab/nim2book-back/internal/services/word_aligner/align"
	mock "github.com/stretchr/testify/mock"
)

// NewMockS3 creates a new instance of MockS3. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3 {
	mock := &MockS3{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3 is an autogenerated mock type for the S3 type
type MockS3 struct {
	mock.Mock
}

type MockS3_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3) EXPECT() *MockS3_Expecter {
	return &MockS3_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockS3
func (_mock *MockS3) Check(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockS3_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - path string
func (_e *MockS3_Expecter) Check(path interface{}) *MockS3_Check_Call {
	return &MockS3_Check_Call{Call: _e.mock.On("Check", path)}
}

func (_c *MockS3_Check_Call) Run(run func(path string)) *MockS3_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockS3_Check_Call) Return(err error) *MockS3_Check_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3_Check_Call) RunAndReturn(run func(path string) error) *MockS3_Check_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockS3
func (_mock *MockS3) Upload(path string, data []byte) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockS3_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - path string
//   - data []byte
func (_e *MockS3_Expecter) Upload(path interface{}, data interface{}) *MockS3_Upload_Call {
	return &MockS3_Upload_Call{Call: _e.mock.On("Upload", path, data)}
}

func (_c *MockS3_Upload_Call) Run(run func(path string, data []byte)) *MockS3_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3_Upload_Call) Return(err error) *MockS3_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3_Upload_Call) RunAndReturn(run func(path string, data []byte) error) *MockS3_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookRepository creates a new instance of MockBookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookRepository {
	mock := &MockBookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookRepository is an autogenerated mock type for the BookRepository type
type MockBookRepository struct {
	mock.Mock
}

type MockBookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookRepository) EXPECT() *MockBookRepository_Expecter {
	return &MockBookRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockBookRepository
func (_mock *MockBookRepository) Create(ctx context.Context, book *domain.Book) (*domain.Book, error) {
	ret := _mock.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Book) (*domain.Book, error)); ok {
		return returnFunc(ctx, book)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Book) *domain.Book); ok {
		r0 = returnFunc(ctx, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Book) error); ok {
		r1 = returnFunc(ctx, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - book *domain.Book
func (_e *MockBookRepository_Expecter) Create(ctx interface{}, book interface{}) *MockBookRepository_Create_Call {
	return &MockBookRepository_Create_Call{Call: _e.mock.On("Create", ctx, book)}
}

func (_c *MockBookRepository_Create_Call) Run(run func(ctx context.Context, book *domain.Book)) *MockBookRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Book
		if args[1] != nil {
			arg1 = args[1].(*domain.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookRepository_Create_Call) Return(book1 *domain.Book, err error) *MockBookRepository_Create_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockBookRepository_Create_Call) RunAndReturn(run func(ctx context.Context, book *domain.Book) (*domain.Book, error)) *MockBookRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChapter provides a mock function for the type MockBookRepository
func (_mock *MockBookRepository) CreateChapter(ctx context.Context, chapter *domain.BookChapter) (*domain.BookChapter, error) {
	ret := _mock.Called(ctx, chapter)

	if len(ret) == 0 {
		panic("no return value specified for CreateChapter")
	}

	var r0 *domain.BookChapter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.BookChapter) (*domain.BookChapter, error)); ok {
		return returnFunc(ctx, chapter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.BookChapter) *domain.BookChapter); ok {
		r0 = returnFunc(ctx, chapter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BookChapter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.BookChapter) error); ok {
		r1 = returnFunc(ctx, chapter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookRepository_CreateChapter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChapter'
type MockBookRepository_CreateChapter_Call struct {
	*mock.Call
}

// CreateChapter is a helper method to define mock.On call
//   - ctx context.Context
//   - chapter *domain.BookChapter
func (_e *MockBookRepository_Expecter) CreateChapter(ctx interface{}, chapter interface{}) *MockBookRepository_CreateChapter_Call {
	return &MockBookRepository_CreateChapter_Call{Call: _e.mock.On("CreateChapter", ctx, chapter)}
}

func (_c *MockBookRepository_CreateChapter_Call) Run(run func(ctx context.Context, chapter *domain.BookChapter)) *MockBookRepository_CreateChapter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.BookChapter
		if args[1] != nil {
			arg1 = args[1].(*domain.BookChapter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookRepository_CreateChapter_Call) Return(bookChapter *domain.BookChapter, err error) *MockBookRepository_CreateChapter_Call {
	_c.Call.Return(bookChapter, err)
	return _c
}

func (_c *MockBookRepository_CreateChapter_Call) RunAndReturn(run func(ctx context.Context, chapter *domain.BookChapter) (*domain.BookChapter, error)) *MockBookRepository_CreateChapter_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAuthorAndTitle provides a mock function for the type MockBookRepository
func (_mock *MockBookRepository) GetByAuthorAndTitle(ctx context.Context, authorName string, title string) (*domain.Book, error) {
	ret := _mock.Called(ctx, authorName, title)

	if len(ret) == 0 {
		panic("no return value specified for GetByAuthorAndTitle")
	}

	var r0 *domain.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Book, error)); ok {
		return returnFunc(ctx, authorName, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Book); ok {
		r0 = returnFunc(ctx, authorName, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, authorName, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookRepository_GetByAuthorAndTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAuthorAndTitle'
type MockBookRepository_GetByAuthorAndTitle_Call struct {
	*mock.Call
}

// GetByAuthorAndTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - authorName string
//   - title string
func (_e *MockBookRepository_Expecter) GetByAuthorAndTitle(ctx interface{}, authorName interface{}, title interface{}) *MockBookRepository_GetByAuthorAndTitle_Call {
	return &MockBookRepository_GetByAuthorAndTitle_Call{Call: _e.mock.On("GetByAuthorAndTitle", ctx, authorName, title)}
}

func (_c *MockBookRepository_GetByAuthorAndTitle_Call) Run(run func(ctx context.Context, authorName string, title string)) *MockBookRepository_GetByAuthorAndTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookRepository_GetByAuthorAndTitle_Call) Return(book *domain.Book, err error) *MockBookRepository_GetByAuthorAndTitle_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockBookRepository_GetByAuthorAndTitle_Call) RunAndReturn(run func(ctx context.Context, authorName string, title string) (*domain.Book, error)) *MockBookRepository_GetByAuthorAndTitle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorRepository creates a new instance of MockAuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorRepository {
	mock := &MockAuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorRepository is an autogenerated mock type for the AuthorRepository type
type MockAuthorRepository struct {
	mock.Mock
}

type MockAuthorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorRepository) EXPECT() *MockAuthorRepository_Expecter {
	return &MockAuthorRepository_Expecter{mock: &_m.Mock}
}

// GetOrCreate provides a mock function for the type MockAuthorRepository
func (_mock *MockAuthorRepository) GetOrCreate(ctx context.Context, name string) (*domain.Author, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *domain.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Author, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Author); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthorRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockAuthorRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAuthorRepository_Expecter) GetOrCreate(ctx interface{}, name interface{}) *MockAuthorRepository_GetOrCreate_Call {
	return &MockAuthorRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, name)}
}

func (_c *MockAuthorRepository_GetOrCreate_Call) Run(run func(ctx context.Context, name string)) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorRepository_GetOrCreate_Call) Return(author *domain.Author, err error) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockAuthorRepository_GetOrCreate_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.Author, error)) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWordAligner creates a new instance of MockWordAligner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWordAligner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWordAligner {
	mock := &MockWordAligner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWordAligner is an autogenerated mock type for the WordAligner type
type MockWordAligner struct {
	mock.Mock
}

type MockWordAligner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWordAligner) EXPECT() *MockWordAligner_Expecter {
	return &MockWordAligner_Expecter{mock: &_m.Mock}
}

// Align provides a mock function for the type MockWordAligner
func (_mock *MockWordAligner) Align(input *align.Input) (*align.Output, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Align")
	}

	var r0 *align.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*align.Input) (*align.Output, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(*align.Input) *align.Output); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*align.Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*align.Input) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordAligner_Align_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Align'
type MockWordAligner_Align_Call struct {
	*mock.Call
}

// Align is a helper method to define mock.On call
//   - input *align.Input
func (_e *MockWordAligner_Expecter) Align(input interface{}) *MockWordAligner_Align_Call {
	return &MockWordAligner_Align_Call{Call: _e.mock.On("Align", input)}
}

func (_c *MockWordAligner_Align_Call) Run(run func(input *align.Input)) *MockWordAligner_Align_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *align.Input
		if args[0] != nil {
			arg0 = args[0].(*align.Input)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWordAligner_Align_Call) Return(output *align.Output, err error) *MockWordAligner_Align_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockWordAligner_Align_Call) RunAndReturn(run func(input *align.Input) (*align.Output, error)) *MockWordAligner_Align_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTranslator creates a new instance of MockTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslator {
	mock := &MockTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranslator is an autogenerated mock type for the Translator type
type MockTranslator struct {
	mock.Mock
}

type MockTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslator) EXPECT() *MockTranslator_Expecter {
	return &MockTranslator_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function for the type MockTranslator
func (_mock *MockTranslator) Translate(input *translate.Input) (*translate.Output, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 *translate.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*translate.Input) (*translate.Output, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(*translate.Input) *translate.Output); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*translate.Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*translate.Input) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranslator_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockTranslator_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - input *translate.Input
func (_e *MockTranslator_Expecter) Translate(input interface{}) *MockTranslator_Translate_Call {
	return &MockTranslator_Translate_Call{Call: _e.mock.On("Translate", input)}
}

func (_c *MockTranslator_Translate_Call) Run(run func(input *translate.Input)) *MockTranslator_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *translate.Input
		if args[0] != nil {
			arg0 = args[0].(*translate.Input)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranslator_Translate_Call) Return(output *translate.Output, err error) *MockTranslator_Translate_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockTranslator_Translate_Call) RunAndReturn(run func(input *translate.Input) (*translate.Output, error)) *MockTranslator_Translate_Call {
	_c.Call.Return(run)
	return _c
}
