// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthorRepository creates a new instance of MockAuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorRepository {
	mock := &MockAuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorRepository is an autogenerated mock type for the AuthorRepository type
type MockAuthorRepository struct {
	mock.Mock
}

type MockAuthorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorRepository) EXPECT() *MockAuthorRepository_Expecter {
	return &MockAuthorRepository_Expecter{mock: &_m.Mock}
}

// GetOrCreate provides a mock function for the type MockAuthorRepository
func (_mock *MockAuthorRepository) GetOrCreate(ctx context.Context, name string) (*domain.Author, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *domain.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Author, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Author); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthorRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockAuthorRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAuthorRepository_Expecter) GetOrCreate(ctx interface{}, name interface{}) *MockAuthorRepository_GetOrCreate_Call {
	return &MockAuthorRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, name)}
}

func (_c *MockAuthorRepository_GetOrCreate_Call) Run(run func(ctx context.Context, name string)) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorRepository_GetOrCreate_Call) Return(author *domain.Author, err error) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockAuthorRepository_GetOrCreate_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.Author, error)) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}
