// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nimyab/nim2book-back/internal/services/word_aligner/align"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWordAligner creates a new instance of MockWordAligner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWordAligner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWordAligner {
	mock := &MockWordAligner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWordAligner is an autogenerated mock type for the WordAligner type
type MockWordAligner struct {
	mock.Mock
}

type MockWordAligner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWordAligner) EXPECT() *MockWordAligner_Expecter {
	return &MockWordAligner_Expecter{mock: &_m.Mock}
}

// Align provides a mock function for the type MockWordAligner
func (_mock *MockWordAligner) Align(input *align.Input) (*align.Output, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Align")
	}

	var r0 *align.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*align.Input) (*align.Output, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(*align.Input) *align.Output); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*align.Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*align.Input) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordAligner_Align_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Align'
type MockWordAligner_Align_Call struct {
	*mock.Call
}

// Align is a helper method to define mock.On call
//   - input *align.Input
func (_e *MockWordAligner_Expecter) Align(input interface{}) *MockWordAligner_Align_Call {
	return &MockWordAligner_Align_Call{Call: _e.mock.On("Align", input)}
}

func (_c *MockWordAligner_Align_Call) Run(run func(input *align.Input)) *MockWordAligner_Align_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *align.Input
		if args[0] != nil {
			arg0 = args[0].(*align.Input)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWordAligner_Align_Call) Return(output *align.Output, err error) *MockWordAligner_Align_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockWordAligner_Align_Call) RunAndReturn(run func(input *align.Input) (*align.Output, error)) *MockWordAligner_Align_Call {
	_c.Call.Return(run)
	return _c
}
