// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dictionary.sql

package sqlc

import (
	"context"
)

const createDictionaryData = `-- name: CreateDictionaryData :exec
insert into dictionary (text, lang, content)
values ($1, $2, $3)
`

type CreateDictionaryDataParams struct {
	Text    string
	Lang    string
	Content []byte
}

func (q *Queries) CreateDictionaryData(ctx context.Context, arg CreateDictionaryDataParams) error {
	_, err := q.db.Exec(ctx, createDictionaryData, arg.Text, arg.Lang, arg.Content)
	return err
}

const dictionaryDataExists = `-- name: DictionaryDataExists :one
select exists(
    select id
    from dictionary
    where text = $1
      and lang = $2
  )
`

type DictionaryDataExistsParams struct {
	Text string
	Lang string
}

func (q *Queries) DictionaryDataExists(ctx context.Context, arg DictionaryDataExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, dictionaryDataExists, arg.Text, arg.Lang)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDictionaryData = `-- name: GetDictionaryData :one
select content
from dictionary
where text = $1
  and lang = $2
`

type GetDictionaryDataParams struct {
	Text string
	Lang string
}

func (q *Queries) GetDictionaryData(ctx context.Context, arg GetDictionaryDataParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDictionaryData, arg.Text, arg.Lang)
	var content []byte
	err := row.Scan(&content)
	return content, err
}
