// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fcm_token.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFcmToken = `-- name: AddFcmToken :one
insert into fcm_tokens (token, user_id)
values ($1, $2)
returning token,
  user_id,
  create_at
`

type AddFcmTokenParams struct {
	Token  string
	UserID pgtype.UUID
}

func (q *Queries) AddFcmToken(ctx context.Context, arg AddFcmTokenParams) (FcmToken, error) {
	row := q.db.QueryRow(ctx, addFcmToken, arg.Token, arg.UserID)
	var i FcmToken
	err := row.Scan(&i.Token, &i.UserID, &i.CreateAt)
	return i, err
}

const deleteFcmToken = `-- name: DeleteFcmToken :exec
delete from fcm_tokens
where token = $1
  and user_id = $2
`

type DeleteFcmTokenParams struct {
	Token  string
	UserID pgtype.UUID
}

func (q *Queries) DeleteFcmToken(ctx context.Context, arg DeleteFcmTokenParams) error {
	_, err := q.db.Exec(ctx, deleteFcmToken, arg.Token, arg.UserID)
	return err
}

const getFcmTokenByToken = `-- name: GetFcmTokenByToken :one
select token, user_id, create_at
from fcm_tokens
where token = $1
`

func (q *Queries) GetFcmTokenByToken(ctx context.Context, token string) (FcmToken, error) {
	row := q.db.QueryRow(ctx, getFcmTokenByToken, token)
	var i FcmToken
	err := row.Scan(&i.Token, &i.UserID, &i.CreateAt)
	return i, err
}

const getFcmTokensByUserId = `-- name: GetFcmTokensByUserId :many
select token, user_id, create_at
from fcm_tokens
where user_id = $1
`

func (q *Queries) GetFcmTokensByUserId(ctx context.Context, userID pgtype.UUID) ([]FcmToken, error) {
	rows, err := q.db.Query(ctx, getFcmTokensByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FcmToken
	for rows.Next() {
		var i FcmToken
		if err := rows.Scan(&i.Token, &i.UserID, &i.CreateAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
