// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: genre.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGenre = `-- name: CreateGenre :one
insert into genres (name)
values ($1)
returning id, name
`

func (q *Queries) CreateGenre(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, createGenre, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteGenre = `-- name: DeleteGenre :exec
delete from genres
where id = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGenre, id)
	return err
}

const getAllGenres = `-- name: GetAllGenres :many
select id, name
from genres
`

func (q *Queries) GetAllGenres(ctx context.Context) ([]Genre, error) {
	rows, err := q.db.Query(ctx, getAllGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Genre
	for rows.Next() {
		var i Genre
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenreById = `-- name: GetGenreById :one
select id, name
from genres
where id = $1
`

func (q *Queries) GetGenreById(ctx context.Context, id pgtype.UUID) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenreById, id)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getGenreByName = `-- name: GetGenreByName :one
select id, name
from genres
where name = $1
`

func (q *Queries) GetGenreByName(ctx context.Context, name string) (Genre, error) {
	row := q.db.QueryRow(ctx, getGenreByName, name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateGenre = `-- name: UpdateGenre :one
update genres
set name = $2
where id = $1
returning id, name
`

type UpdateGenreParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpdateGenre(ctx context.Context, arg UpdateGenreParams) (Genre, error) {
	row := q.db.QueryRow(ctx, updateGenre, arg.ID, arg.Name)
	var i Genre
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
