// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/nimyab/nim2book-back/internal/domain"
)

type Book struct {
	ID           domain.Id
	Title        string
	Author       string
	ChapterPaths []string
	Cover        *string
}

type Dictionary struct {
	ID      domain.Id
	Text    string
	Lang    string
	Content []byte
}

type EmailPasswordAccount struct {
	ID           domain.Id
	Email        string
	PasswordHash string
}

type FcmToken struct {
	Token    string
	UserID   uuid.UUID
	CreateAt pgtype.Timestamptz
}

type GoogleAccount struct {
	Sub           string
	Email         string
	EmailVerified bool
	Name          string
	Picture       *string
}

type User struct {
	ID                     domain.Id
	IsAdmin                bool
	IsVip                  bool
	Metadata               []byte
	GoogleAccountSub       *string
	EmailPasswordAccountID uuid.UUID
}
