// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package translated_logic

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/services/libretranslate/translate"
	"github.com/nimyab/nim2book-back/proto/word_aligner"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockWordAligner creates a new instance of MockWordAligner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWordAligner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWordAligner {
	mock := &MockWordAligner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWordAligner is an autogenerated mock type for the WordAligner type
type MockWordAligner struct {
	mock.Mock
}

type MockWordAligner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWordAligner) EXPECT() *MockWordAligner_Expecter {
	return &MockWordAligner_Expecter{mock: &_m.Mock}
}

// Align provides a mock function for the type MockWordAligner
func (_mock *MockWordAligner) Align(ctx context.Context, in *word_aligner.AlignRequest, opts ...grpc.CallOption) (*word_aligner.AlignResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Align")
	}

	var r0 *word_aligner.AlignResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *word_aligner.AlignRequest, ...grpc.CallOption) (*word_aligner.AlignResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *word_aligner.AlignRequest, ...grpc.CallOption) *word_aligner.AlignResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*word_aligner.AlignResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *word_aligner.AlignRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordAligner_Align_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Align'
type MockWordAligner_Align_Call struct {
	*mock.Call
}

// Align is a helper method to define mock.On call
//   - ctx context.Context
//   - in *word_aligner.AlignRequest
//   - opts ...grpc.CallOption
func (_e *MockWordAligner_Expecter) Align(ctx interface{}, in interface{}, opts ...interface{}) *MockWordAligner_Align_Call {
	return &MockWordAligner_Align_Call{Call: _e.mock.On("Align",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockWordAligner_Align_Call) Run(run func(ctx context.Context, in *word_aligner.AlignRequest, opts ...grpc.CallOption)) *MockWordAligner_Align_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *word_aligner.AlignRequest
		if args[1] != nil {
			arg1 = args[1].(*word_aligner.AlignRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWordAligner_Align_Call) Return(alignResponse *word_aligner.AlignResponse, err error) *MockWordAligner_Align_Call {
	_c.Call.Return(alignResponse, err)
	return _c
}

func (_c *MockWordAligner_Align_Call) RunAndReturn(run func(ctx context.Context, in *word_aligner.AlignRequest, opts ...grpc.CallOption) (*word_aligner.AlignResponse, error)) *MockWordAligner_Align_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTranslator creates a new instance of MockTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslator {
	mock := &MockTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranslator is an autogenerated mock type for the Translator type
type MockTranslator struct {
	mock.Mock
}

type MockTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslator) EXPECT() *MockTranslator_Expecter {
	return &MockTranslator_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function for the type MockTranslator
func (_mock *MockTranslator) Translate(input *translate.Input) (*translate.Output, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 *translate.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*translate.Input) (*translate.Output, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(*translate.Input) *translate.Output); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*translate.Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*translate.Input) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranslator_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockTranslator_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - input *translate.Input
func (_e *MockTranslator_Expecter) Translate(input interface{}) *MockTranslator_Translate_Call {
	return &MockTranslator_Translate_Call{Call: _e.mock.On("Translate", input)}
}

func (_c *MockTranslator_Translate_Call) Run(run func(input *translate.Input)) *MockTranslator_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *translate.Input
		if args[0] != nil {
			arg0 = args[0].(*translate.Input)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranslator_Translate_Call) Return(output *translate.Output, err error) *MockTranslator_Translate_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockTranslator_Translate_Call) RunAndReturn(run func(input *translate.Input) (*translate.Output, error)) *MockTranslator_Translate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockThrottler creates a new instance of MockThrottler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThrottler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThrottler {
	mock := &MockThrottler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockThrottler is an autogenerated mock type for the Throttler type
type MockThrottler struct {
	mock.Mock
}

type MockThrottler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThrottler) EXPECT() *MockThrottler_Expecter {
	return &MockThrottler_Expecter{mock: &_m.Mock}
}

// Throttle provides a mock function for the type MockThrottler
func (_mock *MockThrottler) Throttle() {
	_mock.Called()
	return
}

// MockThrottler_Throttle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Throttle'
type MockThrottler_Throttle_Call struct {
	*mock.Call
}

// Throttle is a helper method to define mock.On call
func (_e *MockThrottler_Expecter) Throttle() *MockThrottler_Throttle_Call {
	return &MockThrottler_Throttle_Call{Call: _e.mock.On("Throttle")}
}

func (_c *MockThrottler_Throttle_Call) Run(run func()) *MockThrottler_Throttle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockThrottler_Throttle_Call) Return() *MockThrottler_Throttle_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockThrottler_Throttle_Call) RunAndReturn(run func()) *MockThrottler_Throttle_Call {
	_c.Run(run)
	return _c
}
