// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package get_chapter

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockS3 creates a new instance of MockS3. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3 {
	mock := &MockS3{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3 is an autogenerated mock type for the S3 type
type MockS3 struct {
	mock.Mock
}

type MockS3_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3) EXPECT() *MockS3_Expecter {
	return &MockS3_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockS3
func (_mock *MockS3) Get(path string) ([]byte, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockS3_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockS3_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - path string
func (_e *MockS3_Expecter) Get(path interface{}) *MockS3_Get_Call {
	return &MockS3_Get_Call{Call: _e.mock.On("Get", path)}
}

func (_c *MockS3_Get_Call) Run(run func(path string)) *MockS3_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockS3_Get_Call) Return(bytes []byte, err error) *MockS3_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockS3_Get_Call) RunAndReturn(run func(path string) ([]byte, error)) *MockS3_Get_Call {
	_c.Call.Return(run)
	return _c
}
