// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockThrottlerFunc is an autogenerated mock type for the ThrottlerFunc type
type MockThrottlerFunc struct {
	mock.Mock
}

type MockThrottlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThrottlerFunc) EXPECT() *MockThrottlerFunc_Expecter {
	return &MockThrottlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *MockThrottlerFunc) Execute() {
	_m.Called()
}

// MockThrottlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockThrottlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockThrottlerFunc_Expecter) Execute() *MockThrottlerFunc_Execute_Call {
	return &MockThrottlerFunc_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockThrottlerFunc_Execute_Call) Run(run func()) *MockThrottlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockThrottlerFunc_Execute_Call) Return() *MockThrottlerFunc_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockThrottlerFunc_Execute_Call) RunAndReturn(run func()) *MockThrottlerFunc_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockThrottlerFunc creates a new instance of MockThrottlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThrottlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThrottlerFunc {
	mock := &MockThrottlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
