// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/nimyab/nim2book-back/internal/services/libretranslate/translate"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTranslator creates a new instance of MockTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranslator {
	mock := &MockTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTranslator is an autogenerated mock type for the Translator type
type MockTranslator struct {
	mock.Mock
}

type MockTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranslator) EXPECT() *MockTranslator_Expecter {
	return &MockTranslator_Expecter{mock: &_m.Mock}
}

// Translate provides a mock function for the type MockTranslator
func (_mock *MockTranslator) Translate(input *translate.Input) (*translate.Output, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 *translate.Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*translate.Input) (*translate.Output, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(*translate.Input) *translate.Output); ok {
		r0 = returnFunc(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*translate.Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*translate.Input) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTranslator_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockTranslator_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - input *translate.Input
func (_e *MockTranslator_Expecter) Translate(input interface{}) *MockTranslator_Translate_Call {
	return &MockTranslator_Translate_Call{Call: _e.mock.On("Translate", input)}
}

func (_c *MockTranslator_Translate_Call) Run(run func(input *translate.Input)) *MockTranslator_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *translate.Input
		if args[0] != nil {
			arg0 = args[0].(*translate.Input)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTranslator_Translate_Call) Return(output *translate.Output, err error) *MockTranslator_Translate_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockTranslator_Translate_Call) RunAndReturn(run func(input *translate.Input) (*translate.Output, error)) *MockTranslator_Translate_Call {
	_c.Call.Return(run)
	return _c
}
