// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nimyab/nim2book-back/proto/word_aligner"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockWordAligner creates a new instance of MockWordAligner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWordAligner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWordAligner {
	mock := &MockWordAligner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWordAligner is an autogenerated mock type for the WordAligner type
type MockWordAligner struct {
	mock.Mock
}

type MockWordAligner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWordAligner) EXPECT() *MockWordAligner_Expecter {
	return &MockWordAligner_Expecter{mock: &_m.Mock}
}

// Align provides a mock function for the type MockWordAligner
func (_mock *MockWordAligner) Align(ctx context.Context, in *word_aligner.AlignRequest, opts ...grpc.CallOption) (*word_aligner.AlignResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Align")
	}

	var r0 *word_aligner.AlignResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *word_aligner.AlignRequest, ...grpc.CallOption) (*word_aligner.AlignResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *word_aligner.AlignRequest, ...grpc.CallOption) *word_aligner.AlignResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*word_aligner.AlignResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *word_aligner.AlignRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWordAligner_Align_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Align'
type MockWordAligner_Align_Call struct {
	*mock.Call
}

// Align is a helper method to define mock.On call
//   - ctx context.Context
//   - in *word_aligner.AlignRequest
//   - opts ...grpc.CallOption
func (_e *MockWordAligner_Expecter) Align(ctx interface{}, in interface{}, opts ...interface{}) *MockWordAligner_Align_Call {
	return &MockWordAligner_Align_Call{Call: _e.mock.On("Align",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockWordAligner_Align_Call) Run(run func(ctx context.Context, in *word_aligner.AlignRequest, opts ...grpc.CallOption)) *MockWordAligner_Align_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *word_aligner.AlignRequest
		if args[1] != nil {
			arg1 = args[1].(*word_aligner.AlignRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWordAligner_Align_Call) Return(alignResponse *word_aligner.AlignResponse, err error) *MockWordAligner_Align_Call {
	_c.Call.Return(alignResponse, err)
	return _c
}

func (_c *MockWordAligner_Align_Call) RunAndReturn(run func(ctx context.Context, in *word_aligner.AlignRequest, opts ...grpc.CallOption) (*word_aligner.AlignResponse, error)) *MockWordAligner_Align_Call {
	_c.Call.Return(run)
	return _c
}
