// Code generated by ent, DO NOT EDIT.

package personalbook

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the personalbook type in the database.
	Label = "personal_book"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldCoverURL holds the string denoting the cover_url field in the database.
	FieldCoverURL = "cover_url"
	// FieldOriginalLang holds the string denoting the original_lang field in the database.
	FieldOriginalLang = "original_lang"
	// FieldTranslatedLang holds the string denoting the translated_lang field in the database.
	FieldTranslatedLang = "translated_lang"
	// FieldProcessStatus holds the string denoting the process_status field in the database.
	FieldProcessStatus = "process_status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAuthor holds the string denoting the author edge name in mutations.
	EdgeAuthor = "author"
	// EdgeGenres holds the string denoting the genres edge name in mutations.
	EdgeGenres = "genres"
	// EdgePersonalBookChapters holds the string denoting the personal_book_chapters edge name in mutations.
	EdgePersonalBookChapters = "personal_book_chapters"
	// Table holds the table name of the personalbook in the database.
	Table = "personal_books"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "personal_books"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_personal_books"
	// AuthorTable is the table that holds the author relation/edge.
	AuthorTable = "personal_books"
	// AuthorInverseTable is the table name for the Author entity.
	// It exists in this package in order to avoid circular dependency with the "author" package.
	AuthorInverseTable = "authors"
	// AuthorColumn is the table column denoting the author relation/edge.
	AuthorColumn = "author_personal_books"
	// GenresTable is the table that holds the genres relation/edge. The primary key declared below.
	GenresTable = "genre_personal_books"
	// GenresInverseTable is the table name for the Genre entity.
	// It exists in this package in order to avoid circular dependency with the "genre" package.
	GenresInverseTable = "genres"
	// PersonalBookChaptersTable is the table that holds the personal_book_chapters relation/edge.
	PersonalBookChaptersTable = "personal_book_chapters"
	// PersonalBookChaptersInverseTable is the table name for the PersonalBookChapter entity.
	// It exists in this package in order to avoid circular dependency with the "personalbookchapter" package.
	PersonalBookChaptersInverseTable = "personal_book_chapters"
	// PersonalBookChaptersColumn is the table column denoting the personal_book_chapters relation/edge.
	PersonalBookChaptersColumn = "personal_book_personal_book_chapters"
)

// Columns holds all SQL columns for personalbook fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldCoverURL,
	FieldOriginalLang,
	FieldTranslatedLang,
	FieldProcessStatus,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "personal_books"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"author_personal_books",
	"user_personal_books",
}

var (
	// GenresPrimaryKey and GenresColumn2 are the table columns denoting the
	// primary key for the genres relation (M2M).
	GenresPrimaryKey = []string{"genre_id", "personal_book_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultOriginalLang holds the default value on creation for the "original_lang" field.
	DefaultOriginalLang string
	// DefaultTranslatedLang holds the default value on creation for the "translated_lang" field.
	DefaultTranslatedLang string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// ProcessStatus defines the type for the "process_status" enum field.
type ProcessStatus string

// ProcessStatusNotStarted is the default value of the ProcessStatus enum.
const DefaultProcessStatus = ProcessStatusNotStarted

// ProcessStatus values.
const (
	ProcessStatusNotStarted ProcessStatus = "not_started"
	ProcessStatusInProgress ProcessStatus = "in_progress"
	ProcessStatusCompleted  ProcessStatus = "completed"
	ProcessStatusFailed     ProcessStatus = "failed"
)

func (ps ProcessStatus) String() string {
	return string(ps)
}

// ProcessStatusValidator is a validator for the "process_status" field enum values. It is called by the builders before save.
func ProcessStatusValidator(ps ProcessStatus) error {
	switch ps {
	case ProcessStatusNotStarted, ProcessStatusInProgress, ProcessStatusCompleted, ProcessStatusFailed:
		return nil
	default:
		return fmt.Errorf("personalbook: invalid enum value for process_status field: %q", ps)
	}
}

// OrderOption defines the ordering options for the PersonalBook queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByCoverURL orders the results by the cover_url field.
func ByCoverURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverURL, opts...).ToFunc()
}

// ByOriginalLang orders the results by the original_lang field.
func ByOriginalLang(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalLang, opts...).ToFunc()
}

// ByTranslatedLang orders the results by the translated_lang field.
func ByTranslatedLang(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTranslatedLang, opts...).ToFunc()
}

// ByProcessStatus orders the results by the process_status field.
func ByProcessStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAuthorField orders the results by author field.
func ByAuthorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorStep(), sql.OrderByField(field, opts...))
	}
}

// ByGenresCount orders the results by genres count.
func ByGenresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGenresStep(), opts...)
	}
}

// ByGenres orders the results by genres terms.
func ByGenres(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGenresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPersonalBookChaptersCount orders the results by personal_book_chapters count.
func ByPersonalBookChaptersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPersonalBookChaptersStep(), opts...)
	}
}

// ByPersonalBookChapters orders the results by personal_book_chapters terms.
func ByPersonalBookChapters(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPersonalBookChaptersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAuthorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
	)
}
func newGenresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GenresInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, GenresTable, GenresPrimaryKey...),
	)
}
func newPersonalBookChaptersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PersonalBookChaptersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PersonalBookChaptersTable, PersonalBookChaptersColumn),
	)
}
