// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenreRepository creates a new instance of MockGenreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenreRepository {
	mock := &MockGenreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenreRepository is an autogenerated mock type for the GenreRepository type
type MockGenreRepository struct {
	mock.Mock
}

type MockGenreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenreRepository) EXPECT() *MockGenreRepository_Expecter {
	return &MockGenreRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockGenreRepository
func (_mock *MockGenreRepository) Delete(ctx context.Context, id domain.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGenreRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGenreRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockGenreRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockGenreRepository_Delete_Call {
	return &MockGenreRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockGenreRepository_Delete_Call) Run(run func(ctx context.Context, id domain.ID)) *MockGenreRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenreRepository_Delete_Call) Return(err error) *MockGenreRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGenreRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) error) *MockGenreRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}
