// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/basicaccount"
	"github.com/nimyab/nim2book-back/ent/user"
)

// BasicAccountCreate is the builder for creating a BasicAccount entity.
type BasicAccountCreate struct {
	config
	mutation *BasicAccountMutation
	hooks    []Hook
}

// SetEmail sets the "email" field.
func (_c *BasicAccountCreate) SetEmail(v string) *BasicAccountCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *BasicAccountCreate) SetPasswordHash(v string) *BasicAccountCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetIsVerified sets the "is_verified" field.
func (_c *BasicAccountCreate) SetIsVerified(v bool) *BasicAccountCreate {
	_c.mutation.SetIsVerified(v)
	return _c
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_c *BasicAccountCreate) SetNillableIsVerified(v *bool) *BasicAccountCreate {
	if v != nil {
		_c.SetIsVerified(*v)
	}
	return _c
}

// SetVerifyLink sets the "verify_link" field.
func (_c *BasicAccountCreate) SetVerifyLink(v string) *BasicAccountCreate {
	_c.mutation.SetVerifyLink(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BasicAccountCreate) SetCreatedAt(v time.Time) *BasicAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BasicAccountCreate) SetNillableCreatedAt(v *time.Time) *BasicAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BasicAccountCreate) SetID(v uuid.UUID) *BasicAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BasicAccountCreate) SetNillableID(v *uuid.UUID) *BasicAccountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *BasicAccountCreate) SetUserID(id uuid.UUID) *BasicAccountCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *BasicAccountCreate) SetNillableUserID(id *uuid.UUID) *BasicAccountCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *BasicAccountCreate) SetUser(v *User) *BasicAccountCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the BasicAccountMutation object of the builder.
func (_c *BasicAccountCreate) Mutation() *BasicAccountMutation {
	return _c.mutation
}

// Save creates the BasicAccount in the database.
func (_c *BasicAccountCreate) Save(ctx context.Context) (*BasicAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BasicAccountCreate) SaveX(ctx context.Context) *BasicAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BasicAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BasicAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BasicAccountCreate) defaults() {
	if _, ok := _c.mutation.IsVerified(); !ok {
		v := basicaccount.DefaultIsVerified
		_c.mutation.SetIsVerified(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := basicaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := basicaccount.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BasicAccountCreate) check() error {
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "BasicAccount.email"`)}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "BasicAccount.password_hash"`)}
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		return &ValidationError{Name: "is_verified", err: errors.New(`ent: missing required field "BasicAccount.is_verified"`)}
	}
	if _, ok := _c.mutation.VerifyLink(); !ok {
		return &ValidationError{Name: "verify_link", err: errors.New(`ent: missing required field "BasicAccount.verify_link"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BasicAccount.created_at"`)}
	}
	return nil
}

func (_c *BasicAccountCreate) sqlSave(ctx context.Context) (*BasicAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BasicAccountCreate) createSpec() (*BasicAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &BasicAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(basicaccount.Table, sqlgraph.NewFieldSpec(basicaccount.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(basicaccount.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(basicaccount.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.IsVerified(); ok {
		_spec.SetField(basicaccount.FieldIsVerified, field.TypeBool, value)
		_node.IsVerified = value
	}
	if value, ok := _c.mutation.VerifyLink(); ok {
		_spec.SetField(basicaccount.FieldVerifyLink, field.TypeString, value)
		_node.VerifyLink = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(basicaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   basicaccount.UserTable,
			Columns: []string{basicaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_basic_account = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BasicAccountCreateBulk is the builder for creating many BasicAccount entities in bulk.
type BasicAccountCreateBulk struct {
	config
	err      error
	builders []*BasicAccountCreate
}

// Save creates the BasicAccount entities in the database.
func (_c *BasicAccountCreateBulk) Save(ctx context.Context) ([]*BasicAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BasicAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BasicAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BasicAccountCreateBulk) SaveX(ctx context.Context) []*BasicAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BasicAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BasicAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
