// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/author"
	"github.com/nimyab/nim2book-back/ent/book"
	"github.com/nimyab/nim2book-back/ent/bookchapter"
	"github.com/nimyab/nim2book-back/ent/genre"
	"github.com/nimyab/nim2book-back/ent/predicate"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *BookUpdate) SetCoverURL(v string) *BookUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *BookUpdate) SetNillableCoverURL(v *string) *BookUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// SetOriginalLang sets the "original_lang" field.
func (_u *BookUpdate) SetOriginalLang(v string) *BookUpdate {
	_u.mutation.SetOriginalLang(v)
	return _u
}

// SetNillableOriginalLang sets the "original_lang" field if the given value is not nil.
func (_u *BookUpdate) SetNillableOriginalLang(v *string) *BookUpdate {
	if v != nil {
		_u.SetOriginalLang(*v)
	}
	return _u
}

// SetTranslatedLang sets the "translated_lang" field.
func (_u *BookUpdate) SetTranslatedLang(v string) *BookUpdate {
	_u.mutation.SetTranslatedLang(v)
	return _u
}

// SetNillableTranslatedLang sets the "translated_lang" field if the given value is not nil.
func (_u *BookUpdate) SetNillableTranslatedLang(v *string) *BookUpdate {
	if v != nil {
		_u.SetTranslatedLang(*v)
	}
	return _u
}

// SetAuthorID sets the "author" edge to the Author entity by ID.
func (_u *BookUpdate) SetAuthorID(id uuid.UUID) *BookUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetNillableAuthorID sets the "author" edge to the Author entity by ID if the given value is not nil.
func (_u *BookUpdate) SetNillableAuthorID(id *uuid.UUID) *BookUpdate {
	if id != nil {
		_u = _u.SetAuthorID(*id)
	}
	return _u
}

// SetAuthor sets the "author" edge to the Author entity.
func (_u *BookUpdate) SetAuthor(v *Author) *BookUpdate {
	return _u.SetAuthorID(v.ID)
}

// AddGenreIDs adds the "genres" edge to the Genre entity by IDs.
func (_u *BookUpdate) AddGenreIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.AddGenreIDs(ids...)
	return _u
}

// AddGenres adds the "genres" edges to the Genre entity.
func (_u *BookUpdate) AddGenres(v ...*Genre) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGenreIDs(ids...)
}

// AddBookChapterIDs adds the "book_chapters" edge to the BookChapter entity by IDs.
func (_u *BookUpdate) AddBookChapterIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.AddBookChapterIDs(ids...)
	return _u
}

// AddBookChapters adds the "book_chapters" edges to the BookChapter entity.
func (_u *BookUpdate) AddBookChapters(v ...*BookChapter) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookChapterIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdate) Mutation() *BookMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the Author entity.
func (_u *BookUpdate) ClearAuthor() *BookUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearGenres clears all "genres" edges to the Genre entity.
func (_u *BookUpdate) ClearGenres() *BookUpdate {
	_u.mutation.ClearGenres()
	return _u
}

// RemoveGenreIDs removes the "genres" edge to Genre entities by IDs.
func (_u *BookUpdate) RemoveGenreIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.RemoveGenreIDs(ids...)
	return _u
}

// RemoveGenres removes "genres" edges to Genre entities.
func (_u *BookUpdate) RemoveGenres(v ...*Genre) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGenreIDs(ids...)
}

// ClearBookChapters clears all "book_chapters" edges to the BookChapter entity.
func (_u *BookUpdate) ClearBookChapters() *BookUpdate {
	_u.mutation.ClearBookChapters()
	return _u
}

// RemoveBookChapterIDs removes the "book_chapters" edge to BookChapter entities by IDs.
func (_u *BookUpdate) RemoveBookChapterIDs(ids ...uuid.UUID) *BookUpdate {
	_u.mutation.RemoveBookChapterIDs(ids...)
	return _u
}

// RemoveBookChapters removes "book_chapters" edges to BookChapter entities.
func (_u *BookUpdate) RemoveBookChapters(v ...*BookChapter) *BookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookChapterIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(book.FieldCoverURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalLang(); ok {
		_spec.SetField(book.FieldOriginalLang, field.TypeString, value)
	}
	if value, ok := _u.mutation.TranslatedLang(); ok {
		_spec.SetField(book.FieldTranslatedLang, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.AuthorTable,
			Columns: []string{book.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.AuthorTable,
			Columns: []string{book.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.GenresTable,
			Columns: book.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGenresIDs(); len(nodes) > 0 && !_u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.GenresTable,
			Columns: book.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GenresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.GenresTable,
			Columns: book.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookChaptersTable,
			Columns: []string{book.BookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookchapter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookChaptersIDs(); len(nodes) > 0 && !_u.mutation.BookChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookChaptersTable,
			Columns: []string{book.BookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookchapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookChaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookChaptersTable,
			Columns: []string{book.BookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookchapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetCoverURL sets the "cover_url" field.
func (_u *BookUpdateOne) SetCoverURL(v string) *BookUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableCoverURL(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// SetOriginalLang sets the "original_lang" field.
func (_u *BookUpdateOne) SetOriginalLang(v string) *BookUpdateOne {
	_u.mutation.SetOriginalLang(v)
	return _u
}

// SetNillableOriginalLang sets the "original_lang" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableOriginalLang(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetOriginalLang(*v)
	}
	return _u
}

// SetTranslatedLang sets the "translated_lang" field.
func (_u *BookUpdateOne) SetTranslatedLang(v string) *BookUpdateOne {
	_u.mutation.SetTranslatedLang(v)
	return _u
}

// SetNillableTranslatedLang sets the "translated_lang" field if the given value is not nil.
func (_u *BookUpdateOne) SetNillableTranslatedLang(v *string) *BookUpdateOne {
	if v != nil {
		_u.SetTranslatedLang(*v)
	}
	return _u
}

// SetAuthorID sets the "author" edge to the Author entity by ID.
func (_u *BookUpdateOne) SetAuthorID(id uuid.UUID) *BookUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetNillableAuthorID sets the "author" edge to the Author entity by ID if the given value is not nil.
func (_u *BookUpdateOne) SetNillableAuthorID(id *uuid.UUID) *BookUpdateOne {
	if id != nil {
		_u = _u.SetAuthorID(*id)
	}
	return _u
}

// SetAuthor sets the "author" edge to the Author entity.
func (_u *BookUpdateOne) SetAuthor(v *Author) *BookUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// AddGenreIDs adds the "genres" edge to the Genre entity by IDs.
func (_u *BookUpdateOne) AddGenreIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.AddGenreIDs(ids...)
	return _u
}

// AddGenres adds the "genres" edges to the Genre entity.
func (_u *BookUpdateOne) AddGenres(v ...*Genre) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGenreIDs(ids...)
}

// AddBookChapterIDs adds the "book_chapters" edge to the BookChapter entity by IDs.
func (_u *BookUpdateOne) AddBookChapterIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.AddBookChapterIDs(ids...)
	return _u
}

// AddBookChapters adds the "book_chapters" edges to the BookChapter entity.
func (_u *BookUpdateOne) AddBookChapters(v ...*BookChapter) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookChapterIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (_u *BookUpdateOne) Mutation() *BookMutation {
	return _u.mutation
}

// ClearAuthor clears the "author" edge to the Author entity.
func (_u *BookUpdateOne) ClearAuthor() *BookUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearGenres clears all "genres" edges to the Genre entity.
func (_u *BookUpdateOne) ClearGenres() *BookUpdateOne {
	_u.mutation.ClearGenres()
	return _u
}

// RemoveGenreIDs removes the "genres" edge to Genre entities by IDs.
func (_u *BookUpdateOne) RemoveGenreIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.RemoveGenreIDs(ids...)
	return _u
}

// RemoveGenres removes "genres" edges to Genre entities.
func (_u *BookUpdateOne) RemoveGenres(v ...*Genre) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGenreIDs(ids...)
}

// ClearBookChapters clears all "book_chapters" edges to the BookChapter entity.
func (_u *BookUpdateOne) ClearBookChapters() *BookUpdateOne {
	_u.mutation.ClearBookChapters()
	return _u
}

// RemoveBookChapterIDs removes the "book_chapters" edge to BookChapter entities by IDs.
func (_u *BookUpdateOne) RemoveBookChapterIDs(ids ...uuid.UUID) *BookUpdateOne {
	_u.mutation.RemoveBookChapterIDs(ids...)
	return _u
}

// RemoveBookChapters removes "book_chapters" edges to BookChapter entities.
func (_u *BookUpdateOne) RemoveBookChapters(v ...*BookChapter) *BookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookChapterIDs(ids...)
}

// Where appends a list predicates to the BookUpdate builder.
func (_u *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Book entity.
func (_u *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(book.FieldCoverURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalLang(); ok {
		_spec.SetField(book.FieldOriginalLang, field.TypeString, value)
	}
	if value, ok := _u.mutation.TranslatedLang(); ok {
		_spec.SetField(book.FieldTranslatedLang, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.AuthorTable,
			Columns: []string{book.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   book.AuthorTable,
			Columns: []string{book.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.GenresTable,
			Columns: book.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGenresIDs(); len(nodes) > 0 && !_u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.GenresTable,
			Columns: book.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GenresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   book.GenresTable,
			Columns: book.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BookChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookChaptersTable,
			Columns: []string{book.BookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookchapter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBookChaptersIDs(); len(nodes) > 0 && !_u.mutation.BookChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookChaptersTable,
			Columns: []string{book.BookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookchapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookChaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.BookChaptersTable,
			Columns: []string{book.BookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bookchapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
