// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/book"
	"github.com/nimyab/nim2book-back/ent/bookchapter"
	"github.com/nimyab/nim2book-back/ent/predicate"
)

// BookChapterUpdate is the builder for updating BookChapter entities.
type BookChapterUpdate struct {
	config
	hooks    []Hook
	mutation *BookChapterMutation
}

// Where appends a list predicates to the BookChapterUpdate builder.
func (_u *BookChapterUpdate) Where(ps ...predicate.BookChapter) *BookChapterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *BookChapterUpdate) SetTitle(v string) *BookChapterUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookChapterUpdate) SetNillableTitle(v *string) *BookChapterUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTranslatedTitle sets the "translated_title" field.
func (_u *BookChapterUpdate) SetTranslatedTitle(v string) *BookChapterUpdate {
	_u.mutation.SetTranslatedTitle(v)
	return _u
}

// SetNillableTranslatedTitle sets the "translated_title" field if the given value is not nil.
func (_u *BookChapterUpdate) SetNillableTranslatedTitle(v *string) *BookChapterUpdate {
	if v != nil {
		_u.SetTranslatedTitle(*v)
	}
	return _u
}

// SetContentURL sets the "content_url" field.
func (_u *BookChapterUpdate) SetContentURL(v string) *BookChapterUpdate {
	_u.mutation.SetContentURL(v)
	return _u
}

// SetNillableContentURL sets the "content_url" field if the given value is not nil.
func (_u *BookChapterUpdate) SetNillableContentURL(v *string) *BookChapterUpdate {
	if v != nil {
		_u.SetContentURL(*v)
	}
	return _u
}

// SetBookID sets the "book" edge to the Book entity by ID.
func (_u *BookChapterUpdate) SetBookID(id uuid.UUID) *BookChapterUpdate {
	_u.mutation.SetBookID(id)
	return _u
}

// SetNillableBookID sets the "book" edge to the Book entity by ID if the given value is not nil.
func (_u *BookChapterUpdate) SetNillableBookID(id *uuid.UUID) *BookChapterUpdate {
	if id != nil {
		_u = _u.SetBookID(*id)
	}
	return _u
}

// SetBook sets the "book" edge to the Book entity.
func (_u *BookChapterUpdate) SetBook(v *Book) *BookChapterUpdate {
	return _u.SetBookID(v.ID)
}

// Mutation returns the BookChapterMutation object of the builder.
func (_u *BookChapterUpdate) Mutation() *BookChapterMutation {
	return _u.mutation
}

// ClearBook clears the "book" edge to the Book entity.
func (_u *BookChapterUpdate) ClearBook() *BookChapterUpdate {
	_u.mutation.ClearBook()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BookChapterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookChapterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BookChapterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookChapterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BookChapterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(bookchapter.Table, bookchapter.Columns, sqlgraph.NewFieldSpec(bookchapter.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(bookchapter.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TranslatedTitle(); ok {
		_spec.SetField(bookchapter.FieldTranslatedTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentURL(); ok {
		_spec.SetField(bookchapter.FieldContentURL, field.TypeString, value)
	}
	if _u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookchapter.BookTable,
			Columns: []string{bookchapter.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookchapter.BookTable,
			Columns: []string{bookchapter.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookchapter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BookChapterUpdateOne is the builder for updating a single BookChapter entity.
type BookChapterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookChapterMutation
}

// SetTitle sets the "title" field.
func (_u *BookChapterUpdateOne) SetTitle(v string) *BookChapterUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BookChapterUpdateOne) SetNillableTitle(v *string) *BookChapterUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetTranslatedTitle sets the "translated_title" field.
func (_u *BookChapterUpdateOne) SetTranslatedTitle(v string) *BookChapterUpdateOne {
	_u.mutation.SetTranslatedTitle(v)
	return _u
}

// SetNillableTranslatedTitle sets the "translated_title" field if the given value is not nil.
func (_u *BookChapterUpdateOne) SetNillableTranslatedTitle(v *string) *BookChapterUpdateOne {
	if v != nil {
		_u.SetTranslatedTitle(*v)
	}
	return _u
}

// SetContentURL sets the "content_url" field.
func (_u *BookChapterUpdateOne) SetContentURL(v string) *BookChapterUpdateOne {
	_u.mutation.SetContentURL(v)
	return _u
}

// SetNillableContentURL sets the "content_url" field if the given value is not nil.
func (_u *BookChapterUpdateOne) SetNillableContentURL(v *string) *BookChapterUpdateOne {
	if v != nil {
		_u.SetContentURL(*v)
	}
	return _u
}

// SetBookID sets the "book" edge to the Book entity by ID.
func (_u *BookChapterUpdateOne) SetBookID(id uuid.UUID) *BookChapterUpdateOne {
	_u.mutation.SetBookID(id)
	return _u
}

// SetNillableBookID sets the "book" edge to the Book entity by ID if the given value is not nil.
func (_u *BookChapterUpdateOne) SetNillableBookID(id *uuid.UUID) *BookChapterUpdateOne {
	if id != nil {
		_u = _u.SetBookID(*id)
	}
	return _u
}

// SetBook sets the "book" edge to the Book entity.
func (_u *BookChapterUpdateOne) SetBook(v *Book) *BookChapterUpdateOne {
	return _u.SetBookID(v.ID)
}

// Mutation returns the BookChapterMutation object of the builder.
func (_u *BookChapterUpdateOne) Mutation() *BookChapterMutation {
	return _u.mutation
}

// ClearBook clears the "book" edge to the Book entity.
func (_u *BookChapterUpdateOne) ClearBook() *BookChapterUpdateOne {
	_u.mutation.ClearBook()
	return _u
}

// Where appends a list predicates to the BookChapterUpdate builder.
func (_u *BookChapterUpdateOne) Where(ps ...predicate.BookChapter) *BookChapterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BookChapterUpdateOne) Select(field string, fields ...string) *BookChapterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BookChapter entity.
func (_u *BookChapterUpdateOne) Save(ctx context.Context) (*BookChapter, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BookChapterUpdateOne) SaveX(ctx context.Context) *BookChapter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BookChapterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BookChapterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *BookChapterUpdateOne) sqlSave(ctx context.Context) (_node *BookChapter, err error) {
	_spec := sqlgraph.NewUpdateSpec(bookchapter.Table, bookchapter.Columns, sqlgraph.NewFieldSpec(bookchapter.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BookChapter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bookchapter.FieldID)
		for _, f := range fields {
			if !bookchapter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bookchapter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(bookchapter.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TranslatedTitle(); ok {
		_spec.SetField(bookchapter.FieldTranslatedTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentURL(); ok {
		_spec.SetField(bookchapter.FieldContentURL, field.TypeString, value)
	}
	if _u.mutation.BookCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookchapter.BookTable,
			Columns: []string{bookchapter.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bookchapter.BookTable,
			Columns: []string{bookchapter.BookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BookChapter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bookchapter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
