// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/author"
	"github.com/nimyab/nim2book-back/ent/book"
)

// Book is the model entity for the Book schema.
type Book struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// CoverURL holds the value of the "cover_url" field.
	CoverURL *string `json:"cover_url,omitempty"`
	// OriginalLang holds the value of the "original_lang" field.
	OriginalLang string `json:"original_lang,omitempty"`
	// TranslatedLang holds the value of the "translated_lang" field.
	TranslatedLang string `json:"translated_lang,omitempty"`
	// ProcessStatus holds the value of the "process_status" field.
	ProcessStatus book.ProcessStatus `json:"process_status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BookQuery when eager-loading is set.
	Edges        BookEdges `json:"edges"`
	author_books *uuid.UUID
	selectValues sql.SelectValues
}

// BookEdges holds the relations/edges for other nodes in the graph.
type BookEdges struct {
	// Author holds the value of the author edge.
	Author *Author `json:"author,omitempty"`
	// Genres holds the value of the genres edge.
	Genres []*Genre `json:"genres,omitempty"`
	// BookChapters holds the value of the book_chapters edge.
	BookChapters []*BookChapter `json:"book_chapters,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookEdges) AuthorOrErr() (*Author, error) {
	if e.Author != nil {
		return e.Author, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: author.Label}
	}
	return nil, &NotLoadedError{edge: "author"}
}

// GenresOrErr returns the Genres value or an error if the edge
// was not loaded in eager-loading.
func (e BookEdges) GenresOrErr() ([]*Genre, error) {
	if e.loadedTypes[1] {
		return e.Genres, nil
	}
	return nil, &NotLoadedError{edge: "genres"}
}

// BookChaptersOrErr returns the BookChapters value or an error if the edge
// was not loaded in eager-loading.
func (e BookEdges) BookChaptersOrErr() ([]*BookChapter, error) {
	if e.loadedTypes[2] {
		return e.BookChapters, nil
	}
	return nil, &NotLoadedError{edge: "book_chapters"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Book) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case book.FieldTitle, book.FieldCoverURL, book.FieldOriginalLang, book.FieldTranslatedLang, book.FieldProcessStatus:
			values[i] = new(sql.NullString)
		case book.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case book.FieldID:
			values[i] = new(uuid.UUID)
		case book.ForeignKeys[0]: // author_books
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Book fields.
func (_m *Book) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case book.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case book.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case book.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				_m.CoverURL = new(string)
				*_m.CoverURL = value.String
			}
		case book.FieldOriginalLang:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_lang", values[i])
			} else if value.Valid {
				_m.OriginalLang = value.String
			}
		case book.FieldTranslatedLang:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field translated_lang", values[i])
			} else if value.Valid {
				_m.TranslatedLang = value.String
			}
		case book.FieldProcessStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field process_status", values[i])
			} else if value.Valid {
				_m.ProcessStatus = book.ProcessStatus(value.String)
			}
		case book.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case book.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field author_books", values[i])
			} else if value.Valid {
				_m.author_books = new(uuid.UUID)
				*_m.author_books = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Book.
// This includes values selected through modifiers, order, etc.
func (_m *Book) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAuthor queries the "author" edge of the Book entity.
func (_m *Book) QueryAuthor() *AuthorQuery {
	return NewBookClient(_m.config).QueryAuthor(_m)
}

// QueryGenres queries the "genres" edge of the Book entity.
func (_m *Book) QueryGenres() *GenreQuery {
	return NewBookClient(_m.config).QueryGenres(_m)
}

// QueryBookChapters queries the "book_chapters" edge of the Book entity.
func (_m *Book) QueryBookChapters() *BookChapterQuery {
	return NewBookClient(_m.config).QueryBookChapters(_m)
}

// Update returns a builder for updating this Book.
// Note that you need to call Book.Unwrap() before calling this method if this Book
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Book) Update() *BookUpdateOne {
	return NewBookClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Book entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Book) Unwrap() *Book {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Book is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Book) String() string {
	var builder strings.Builder
	builder.WriteString("Book(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.CoverURL; v != nil {
		builder.WriteString("cover_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("original_lang=")
	builder.WriteString(_m.OriginalLang)
	builder.WriteString(", ")
	builder.WriteString("translated_lang=")
	builder.WriteString(_m.TranslatedLang)
	builder.WriteString(", ")
	builder.WriteString("process_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProcessStatus))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Books is a parsable slice of Book.
type Books []*Book
