// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/dictionary"
)

// Dictionary is the model entity for the Dictionary schema.
type Dictionary struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// PartOfSpeech holds the value of the "part_of_speech" field.
	PartOfSpeech string `json:"part_of_speech,omitempty"`
	// Transcription holds the value of the "transcription" field.
	Transcription string `json:"transcription,omitempty"`
	// FromLangCode holds the value of the "from_lang_code" field.
	FromLangCode string `json:"from_lang_code,omitempty"`
	// ToLangCode holds the value of the "to_lang_code" field.
	ToLangCode string `json:"to_lang_code,omitempty"`
	// Translations holds the value of the "translations" field.
	Translations []string `json:"translations,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DictionaryQuery when eager-loading is set.
	Edges        DictionaryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DictionaryEdges holds the relations/edges for other nodes in the graph.
type DictionaryEdges struct {
	// DictionaryExamples holds the value of the dictionary_examples edge.
	DictionaryExamples []*DictionaryExample `json:"dictionary_examples,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DictionaryExamplesOrErr returns the DictionaryExamples value or an error if the edge
// was not loaded in eager-loading.
func (e DictionaryEdges) DictionaryExamplesOrErr() ([]*DictionaryExample, error) {
	if e.loadedTypes[0] {
		return e.DictionaryExamples, nil
	}
	return nil, &NotLoadedError{edge: "dictionary_examples"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dictionary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dictionary.FieldTranslations:
			values[i] = new([]byte)
		case dictionary.FieldText, dictionary.FieldPartOfSpeech, dictionary.FieldTranscription, dictionary.FieldFromLangCode, dictionary.FieldToLangCode:
			values[i] = new(sql.NullString)
		case dictionary.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case dictionary.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dictionary fields.
func (_m *Dictionary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dictionary.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case dictionary.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case dictionary.FieldPartOfSpeech:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field part_of_speech", values[i])
			} else if value.Valid {
				_m.PartOfSpeech = value.String
			}
		case dictionary.FieldTranscription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field transcription", values[i])
			} else if value.Valid {
				_m.Transcription = value.String
			}
		case dictionary.FieldFromLangCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_lang_code", values[i])
			} else if value.Valid {
				_m.FromLangCode = value.String
			}
		case dictionary.FieldToLangCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_lang_code", values[i])
			} else if value.Valid {
				_m.ToLangCode = value.String
			}
		case dictionary.FieldTranslations:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field translations", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Translations); err != nil {
					return fmt.Errorf("unmarshal field translations: %w", err)
				}
			}
		case dictionary.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Dictionary.
// This includes values selected through modifiers, order, etc.
func (_m *Dictionary) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDictionaryExamples queries the "dictionary_examples" edge of the Dictionary entity.
func (_m *Dictionary) QueryDictionaryExamples() *DictionaryExampleQuery {
	return NewDictionaryClient(_m.config).QueryDictionaryExamples(_m)
}

// Update returns a builder for updating this Dictionary.
// Note that you need to call Dictionary.Unwrap() before calling this method if this Dictionary
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Dictionary) Update() *DictionaryUpdateOne {
	return NewDictionaryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Dictionary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Dictionary) Unwrap() *Dictionary {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dictionary is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Dictionary) String() string {
	var builder strings.Builder
	builder.WriteString("Dictionary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("part_of_speech=")
	builder.WriteString(_m.PartOfSpeech)
	builder.WriteString(", ")
	builder.WriteString("transcription=")
	builder.WriteString(_m.Transcription)
	builder.WriteString(", ")
	builder.WriteString("from_lang_code=")
	builder.WriteString(_m.FromLangCode)
	builder.WriteString(", ")
	builder.WriteString("to_lang_code=")
	builder.WriteString(_m.ToLangCode)
	builder.WriteString(", ")
	builder.WriteString("translations=")
	builder.WriteString(fmt.Sprintf("%v", _m.Translations))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Dictionaries is a parsable slice of Dictionary.
type Dictionaries []*Dictionary
