// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/dictionary"
	"github.com/nimyab/nim2book-back/ent/dictionaryexample"
	"github.com/nimyab/nim2book-back/ent/predicate"
)

// DictionaryExampleUpdate is the builder for updating DictionaryExample entities.
type DictionaryExampleUpdate struct {
	config
	hooks    []Hook
	mutation *DictionaryExampleMutation
}

// Where appends a list predicates to the DictionaryExampleUpdate builder.
func (_u *DictionaryExampleUpdate) Where(ps ...predicate.DictionaryExample) *DictionaryExampleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *DictionaryExampleUpdate) SetText(v string) *DictionaryExampleUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *DictionaryExampleUpdate) SetNillableText(v *string) *DictionaryExampleUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetTranslation sets the "translation" field.
func (_u *DictionaryExampleUpdate) SetTranslation(v string) *DictionaryExampleUpdate {
	_u.mutation.SetTranslation(v)
	return _u
}

// SetNillableTranslation sets the "translation" field if the given value is not nil.
func (_u *DictionaryExampleUpdate) SetNillableTranslation(v *string) *DictionaryExampleUpdate {
	if v != nil {
		_u.SetTranslation(*v)
	}
	return _u
}

// SetTargetPositionStart sets the "target_position_start" field.
func (_u *DictionaryExampleUpdate) SetTargetPositionStart(v int) *DictionaryExampleUpdate {
	_u.mutation.ResetTargetPositionStart()
	_u.mutation.SetTargetPositionStart(v)
	return _u
}

// SetNillableTargetPositionStart sets the "target_position_start" field if the given value is not nil.
func (_u *DictionaryExampleUpdate) SetNillableTargetPositionStart(v *int) *DictionaryExampleUpdate {
	if v != nil {
		_u.SetTargetPositionStart(*v)
	}
	return _u
}

// AddTargetPositionStart adds value to the "target_position_start" field.
func (_u *DictionaryExampleUpdate) AddTargetPositionStart(v int) *DictionaryExampleUpdate {
	_u.mutation.AddTargetPositionStart(v)
	return _u
}

// SetTargetPositionEnd sets the "target_position_end" field.
func (_u *DictionaryExampleUpdate) SetTargetPositionEnd(v int) *DictionaryExampleUpdate {
	_u.mutation.ResetTargetPositionEnd()
	_u.mutation.SetTargetPositionEnd(v)
	return _u
}

// SetNillableTargetPositionEnd sets the "target_position_end" field if the given value is not nil.
func (_u *DictionaryExampleUpdate) SetNillableTargetPositionEnd(v *int) *DictionaryExampleUpdate {
	if v != nil {
		_u.SetTargetPositionEnd(*v)
	}
	return _u
}

// AddTargetPositionEnd adds value to the "target_position_end" field.
func (_u *DictionaryExampleUpdate) AddTargetPositionEnd(v int) *DictionaryExampleUpdate {
	_u.mutation.AddTargetPositionEnd(v)
	return _u
}

// SetDictionaryID sets the "dictionary" edge to the Dictionary entity by ID.
func (_u *DictionaryExampleUpdate) SetDictionaryID(id uuid.UUID) *DictionaryExampleUpdate {
	_u.mutation.SetDictionaryID(id)
	return _u
}

// SetNillableDictionaryID sets the "dictionary" edge to the Dictionary entity by ID if the given value is not nil.
func (_u *DictionaryExampleUpdate) SetNillableDictionaryID(id *uuid.UUID) *DictionaryExampleUpdate {
	if id != nil {
		_u = _u.SetDictionaryID(*id)
	}
	return _u
}

// SetDictionary sets the "dictionary" edge to the Dictionary entity.
func (_u *DictionaryExampleUpdate) SetDictionary(v *Dictionary) *DictionaryExampleUpdate {
	return _u.SetDictionaryID(v.ID)
}

// Mutation returns the DictionaryExampleMutation object of the builder.
func (_u *DictionaryExampleUpdate) Mutation() *DictionaryExampleMutation {
	return _u.mutation
}

// ClearDictionary clears the "dictionary" edge to the Dictionary entity.
func (_u *DictionaryExampleUpdate) ClearDictionary() *DictionaryExampleUpdate {
	_u.mutation.ClearDictionary()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictionaryExampleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryExampleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictionaryExampleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryExampleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictionaryExampleUpdate) check() error {
	if v, ok := _u.mutation.TargetPositionStart(); ok {
		if err := dictionaryexample.TargetPositionStartValidator(v); err != nil {
			return &ValidationError{Name: "target_position_start", err: fmt.Errorf(`ent: validator failed for field "DictionaryExample.target_position_start": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetPositionEnd(); ok {
		if err := dictionaryexample.TargetPositionEndValidator(v); err != nil {
			return &ValidationError{Name: "target_position_end", err: fmt.Errorf(`ent: validator failed for field "DictionaryExample.target_position_end": %w`, err)}
		}
	}
	return nil
}

func (_u *DictionaryExampleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictionaryexample.Table, dictionaryexample.Columns, sqlgraph.NewFieldSpec(dictionaryexample.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(dictionaryexample.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Translation(); ok {
		_spec.SetField(dictionaryexample.FieldTranslation, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetPositionStart(); ok {
		_spec.SetField(dictionaryexample.FieldTargetPositionStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetPositionStart(); ok {
		_spec.AddField(dictionaryexample.FieldTargetPositionStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetPositionEnd(); ok {
		_spec.SetField(dictionaryexample.FieldTargetPositionEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetPositionEnd(); ok {
		_spec.AddField(dictionaryexample.FieldTargetPositionEnd, field.TypeInt, value)
	}
	if _u.mutation.DictionaryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionaryexample.DictionaryTable,
			Columns: []string{dictionaryexample.DictionaryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DictionaryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionaryexample.DictionaryTable,
			Columns: []string{dictionaryexample.DictionaryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionaryexample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictionaryExampleUpdateOne is the builder for updating a single DictionaryExample entity.
type DictionaryExampleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DictionaryExampleMutation
}

// SetText sets the "text" field.
func (_u *DictionaryExampleUpdateOne) SetText(v string) *DictionaryExampleUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *DictionaryExampleUpdateOne) SetNillableText(v *string) *DictionaryExampleUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetTranslation sets the "translation" field.
func (_u *DictionaryExampleUpdateOne) SetTranslation(v string) *DictionaryExampleUpdateOne {
	_u.mutation.SetTranslation(v)
	return _u
}

// SetNillableTranslation sets the "translation" field if the given value is not nil.
func (_u *DictionaryExampleUpdateOne) SetNillableTranslation(v *string) *DictionaryExampleUpdateOne {
	if v != nil {
		_u.SetTranslation(*v)
	}
	return _u
}

// SetTargetPositionStart sets the "target_position_start" field.
func (_u *DictionaryExampleUpdateOne) SetTargetPositionStart(v int) *DictionaryExampleUpdateOne {
	_u.mutation.ResetTargetPositionStart()
	_u.mutation.SetTargetPositionStart(v)
	return _u
}

// SetNillableTargetPositionStart sets the "target_position_start" field if the given value is not nil.
func (_u *DictionaryExampleUpdateOne) SetNillableTargetPositionStart(v *int) *DictionaryExampleUpdateOne {
	if v != nil {
		_u.SetTargetPositionStart(*v)
	}
	return _u
}

// AddTargetPositionStart adds value to the "target_position_start" field.
func (_u *DictionaryExampleUpdateOne) AddTargetPositionStart(v int) *DictionaryExampleUpdateOne {
	_u.mutation.AddTargetPositionStart(v)
	return _u
}

// SetTargetPositionEnd sets the "target_position_end" field.
func (_u *DictionaryExampleUpdateOne) SetTargetPositionEnd(v int) *DictionaryExampleUpdateOne {
	_u.mutation.ResetTargetPositionEnd()
	_u.mutation.SetTargetPositionEnd(v)
	return _u
}

// SetNillableTargetPositionEnd sets the "target_position_end" field if the given value is not nil.
func (_u *DictionaryExampleUpdateOne) SetNillableTargetPositionEnd(v *int) *DictionaryExampleUpdateOne {
	if v != nil {
		_u.SetTargetPositionEnd(*v)
	}
	return _u
}

// AddTargetPositionEnd adds value to the "target_position_end" field.
func (_u *DictionaryExampleUpdateOne) AddTargetPositionEnd(v int) *DictionaryExampleUpdateOne {
	_u.mutation.AddTargetPositionEnd(v)
	return _u
}

// SetDictionaryID sets the "dictionary" edge to the Dictionary entity by ID.
func (_u *DictionaryExampleUpdateOne) SetDictionaryID(id uuid.UUID) *DictionaryExampleUpdateOne {
	_u.mutation.SetDictionaryID(id)
	return _u
}

// SetNillableDictionaryID sets the "dictionary" edge to the Dictionary entity by ID if the given value is not nil.
func (_u *DictionaryExampleUpdateOne) SetNillableDictionaryID(id *uuid.UUID) *DictionaryExampleUpdateOne {
	if id != nil {
		_u = _u.SetDictionaryID(*id)
	}
	return _u
}

// SetDictionary sets the "dictionary" edge to the Dictionary entity.
func (_u *DictionaryExampleUpdateOne) SetDictionary(v *Dictionary) *DictionaryExampleUpdateOne {
	return _u.SetDictionaryID(v.ID)
}

// Mutation returns the DictionaryExampleMutation object of the builder.
func (_u *DictionaryExampleUpdateOne) Mutation() *DictionaryExampleMutation {
	return _u.mutation
}

// ClearDictionary clears the "dictionary" edge to the Dictionary entity.
func (_u *DictionaryExampleUpdateOne) ClearDictionary() *DictionaryExampleUpdateOne {
	_u.mutation.ClearDictionary()
	return _u
}

// Where appends a list predicates to the DictionaryExampleUpdate builder.
func (_u *DictionaryExampleUpdateOne) Where(ps ...predicate.DictionaryExample) *DictionaryExampleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictionaryExampleUpdateOne) Select(field string, fields ...string) *DictionaryExampleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictionaryExample entity.
func (_u *DictionaryExampleUpdateOne) Save(ctx context.Context) (*DictionaryExample, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryExampleUpdateOne) SaveX(ctx context.Context) *DictionaryExample {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictionaryExampleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryExampleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictionaryExampleUpdateOne) check() error {
	if v, ok := _u.mutation.TargetPositionStart(); ok {
		if err := dictionaryexample.TargetPositionStartValidator(v); err != nil {
			return &ValidationError{Name: "target_position_start", err: fmt.Errorf(`ent: validator failed for field "DictionaryExample.target_position_start": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetPositionEnd(); ok {
		if err := dictionaryexample.TargetPositionEndValidator(v); err != nil {
			return &ValidationError{Name: "target_position_end", err: fmt.Errorf(`ent: validator failed for field "DictionaryExample.target_position_end": %w`, err)}
		}
	}
	return nil
}

func (_u *DictionaryExampleUpdateOne) sqlSave(ctx context.Context) (_node *DictionaryExample, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictionaryexample.Table, dictionaryexample.Columns, sqlgraph.NewFieldSpec(dictionaryexample.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictionaryExample.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictionaryexample.FieldID)
		for _, f := range fields {
			if !dictionaryexample.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictionaryexample.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(dictionaryexample.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.Translation(); ok {
		_spec.SetField(dictionaryexample.FieldTranslation, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetPositionStart(); ok {
		_spec.SetField(dictionaryexample.FieldTargetPositionStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetPositionStart(); ok {
		_spec.AddField(dictionaryexample.FieldTargetPositionStart, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetPositionEnd(); ok {
		_spec.SetField(dictionaryexample.FieldTargetPositionEnd, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetPositionEnd(); ok {
		_spec.AddField(dictionaryexample.FieldTargetPositionEnd, field.TypeInt, value)
	}
	if _u.mutation.DictionaryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionaryexample.DictionaryTable,
			Columns: []string{dictionaryexample.DictionaryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DictionaryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionaryexample.DictionaryTable,
			Columns: []string{dictionaryexample.DictionaryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DictionaryExample{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionaryexample.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
