// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/dictionary"
	"github.com/nimyab/nim2book-back/ent/dictionaryexample"
)

// DictionaryCreate is the builder for creating a Dictionary entity.
type DictionaryCreate struct {
	config
	mutation *DictionaryMutation
	hooks    []Hook
}

// SetText sets the "text" field.
func (_c *DictionaryCreate) SetText(v string) *DictionaryCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetPartOfSpeech sets the "part_of_speech" field.
func (_c *DictionaryCreate) SetPartOfSpeech(v string) *DictionaryCreate {
	_c.mutation.SetPartOfSpeech(v)
	return _c
}

// SetTranscription sets the "transcription" field.
func (_c *DictionaryCreate) SetTranscription(v string) *DictionaryCreate {
	_c.mutation.SetTranscription(v)
	return _c
}

// SetFromLangCode sets the "from_lang_code" field.
func (_c *DictionaryCreate) SetFromLangCode(v string) *DictionaryCreate {
	_c.mutation.SetFromLangCode(v)
	return _c
}

// SetToLangCode sets the "to_lang_code" field.
func (_c *DictionaryCreate) SetToLangCode(v string) *DictionaryCreate {
	_c.mutation.SetToLangCode(v)
	return _c
}

// SetTranslations sets the "translations" field.
func (_c *DictionaryCreate) SetTranslations(v []string) *DictionaryCreate {
	_c.mutation.SetTranslations(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DictionaryCreate) SetCreatedAt(v time.Time) *DictionaryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DictionaryCreate) SetNillableCreatedAt(v *time.Time) *DictionaryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DictionaryCreate) SetID(v uuid.UUID) *DictionaryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DictionaryCreate) SetNillableID(v *uuid.UUID) *DictionaryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddDictionaryExampleIDs adds the "dictionary_examples" edge to the DictionaryExample entity by IDs.
func (_c *DictionaryCreate) AddDictionaryExampleIDs(ids ...uuid.UUID) *DictionaryCreate {
	_c.mutation.AddDictionaryExampleIDs(ids...)
	return _c
}

// AddDictionaryExamples adds the "dictionary_examples" edges to the DictionaryExample entity.
func (_c *DictionaryCreate) AddDictionaryExamples(v ...*DictionaryExample) *DictionaryCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDictionaryExampleIDs(ids...)
}

// Mutation returns the DictionaryMutation object of the builder.
func (_c *DictionaryCreate) Mutation() *DictionaryMutation {
	return _c.mutation
}

// Save creates the Dictionary in the database.
func (_c *DictionaryCreate) Save(ctx context.Context) (*Dictionary, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DictionaryCreate) SaveX(ctx context.Context) *Dictionary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DictionaryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dictionary.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dictionary.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DictionaryCreate) check() error {
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Dictionary.text"`)}
	}
	if _, ok := _c.mutation.PartOfSpeech(); !ok {
		return &ValidationError{Name: "part_of_speech", err: errors.New(`ent: missing required field "Dictionary.part_of_speech"`)}
	}
	if _, ok := _c.mutation.Transcription(); !ok {
		return &ValidationError{Name: "transcription", err: errors.New(`ent: missing required field "Dictionary.transcription"`)}
	}
	if _, ok := _c.mutation.FromLangCode(); !ok {
		return &ValidationError{Name: "from_lang_code", err: errors.New(`ent: missing required field "Dictionary.from_lang_code"`)}
	}
	if _, ok := _c.mutation.ToLangCode(); !ok {
		return &ValidationError{Name: "to_lang_code", err: errors.New(`ent: missing required field "Dictionary.to_lang_code"`)}
	}
	if _, ok := _c.mutation.Translations(); !ok {
		return &ValidationError{Name: "translations", err: errors.New(`ent: missing required field "Dictionary.translations"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Dictionary.created_at"`)}
	}
	return nil
}

func (_c *DictionaryCreate) sqlSave(ctx context.Context) (*Dictionary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DictionaryCreate) createSpec() (*Dictionary, *sqlgraph.CreateSpec) {
	var (
		_node = &Dictionary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dictionary.Table, sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(dictionary.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.PartOfSpeech(); ok {
		_spec.SetField(dictionary.FieldPartOfSpeech, field.TypeString, value)
		_node.PartOfSpeech = value
	}
	if value, ok := _c.mutation.Transcription(); ok {
		_spec.SetField(dictionary.FieldTranscription, field.TypeString, value)
		_node.Transcription = value
	}
	if value, ok := _c.mutation.FromLangCode(); ok {
		_spec.SetField(dictionary.FieldFromLangCode, field.TypeString, value)
		_node.FromLangCode = value
	}
	if value, ok := _c.mutation.ToLangCode(); ok {
		_spec.SetField(dictionary.FieldToLangCode, field.TypeString, value)
		_node.ToLangCode = value
	}
	if value, ok := _c.mutation.Translations(); ok {
		_spec.SetField(dictionary.FieldTranslations, field.TypeJSON, value)
		_node.Translations = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dictionary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DictionaryExamplesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dictionary.DictionaryExamplesTable,
			Columns: []string{dictionary.DictionaryExamplesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionaryexample.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DictionaryCreateBulk is the builder for creating many Dictionary entities in bulk.
type DictionaryCreateBulk struct {
	config
	err      error
	builders []*DictionaryCreate
}

// Save creates the Dictionary entities in the database.
func (_c *DictionaryCreateBulk) Save(ctx context.Context) ([]*Dictionary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Dictionary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DictionaryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DictionaryCreateBulk) SaveX(ctx context.Context) []*Dictionary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
