// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/dictionary"
	"github.com/nimyab/nim2book-back/ent/dictionaryexample"
)

// DictionaryExampleCreate is the builder for creating a DictionaryExample entity.
type DictionaryExampleCreate struct {
	config
	mutation *DictionaryExampleMutation
	hooks    []Hook
}

// SetText sets the "text" field.
func (_c *DictionaryExampleCreate) SetText(v string) *DictionaryExampleCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetTranslation sets the "translation" field.
func (_c *DictionaryExampleCreate) SetTranslation(v string) *DictionaryExampleCreate {
	_c.mutation.SetTranslation(v)
	return _c
}

// SetTargetPositionStart sets the "target_position_start" field.
func (_c *DictionaryExampleCreate) SetTargetPositionStart(v int) *DictionaryExampleCreate {
	_c.mutation.SetTargetPositionStart(v)
	return _c
}

// SetTargetPositionEnd sets the "target_position_end" field.
func (_c *DictionaryExampleCreate) SetTargetPositionEnd(v int) *DictionaryExampleCreate {
	_c.mutation.SetTargetPositionEnd(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DictionaryExampleCreate) SetCreatedAt(v time.Time) *DictionaryExampleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DictionaryExampleCreate) SetNillableCreatedAt(v *time.Time) *DictionaryExampleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DictionaryExampleCreate) SetID(v uuid.UUID) *DictionaryExampleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DictionaryExampleCreate) SetNillableID(v *uuid.UUID) *DictionaryExampleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDictionaryID sets the "dictionary" edge to the Dictionary entity by ID.
func (_c *DictionaryExampleCreate) SetDictionaryID(id uuid.UUID) *DictionaryExampleCreate {
	_c.mutation.SetDictionaryID(id)
	return _c
}

// SetNillableDictionaryID sets the "dictionary" edge to the Dictionary entity by ID if the given value is not nil.
func (_c *DictionaryExampleCreate) SetNillableDictionaryID(id *uuid.UUID) *DictionaryExampleCreate {
	if id != nil {
		_c = _c.SetDictionaryID(*id)
	}
	return _c
}

// SetDictionary sets the "dictionary" edge to the Dictionary entity.
func (_c *DictionaryExampleCreate) SetDictionary(v *Dictionary) *DictionaryExampleCreate {
	return _c.SetDictionaryID(v.ID)
}

// Mutation returns the DictionaryExampleMutation object of the builder.
func (_c *DictionaryExampleCreate) Mutation() *DictionaryExampleMutation {
	return _c.mutation
}

// Save creates the DictionaryExample in the database.
func (_c *DictionaryExampleCreate) Save(ctx context.Context) (*DictionaryExample, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DictionaryExampleCreate) SaveX(ctx context.Context) *DictionaryExample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryExampleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryExampleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DictionaryExampleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dictionaryexample.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dictionaryexample.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DictionaryExampleCreate) check() error {
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "DictionaryExample.text"`)}
	}
	if _, ok := _c.mutation.Translation(); !ok {
		return &ValidationError{Name: "translation", err: errors.New(`ent: missing required field "DictionaryExample.translation"`)}
	}
	if _, ok := _c.mutation.TargetPositionStart(); !ok {
		return &ValidationError{Name: "target_position_start", err: errors.New(`ent: missing required field "DictionaryExample.target_position_start"`)}
	}
	if v, ok := _c.mutation.TargetPositionStart(); ok {
		if err := dictionaryexample.TargetPositionStartValidator(v); err != nil {
			return &ValidationError{Name: "target_position_start", err: fmt.Errorf(`ent: validator failed for field "DictionaryExample.target_position_start": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetPositionEnd(); !ok {
		return &ValidationError{Name: "target_position_end", err: errors.New(`ent: missing required field "DictionaryExample.target_position_end"`)}
	}
	if v, ok := _c.mutation.TargetPositionEnd(); ok {
		if err := dictionaryexample.TargetPositionEndValidator(v); err != nil {
			return &ValidationError{Name: "target_position_end", err: fmt.Errorf(`ent: validator failed for field "DictionaryExample.target_position_end": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DictionaryExample.created_at"`)}
	}
	return nil
}

func (_c *DictionaryExampleCreate) sqlSave(ctx context.Context) (*DictionaryExample, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DictionaryExampleCreate) createSpec() (*DictionaryExample, *sqlgraph.CreateSpec) {
	var (
		_node = &DictionaryExample{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dictionaryexample.Table, sqlgraph.NewFieldSpec(dictionaryexample.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(dictionaryexample.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.Translation(); ok {
		_spec.SetField(dictionaryexample.FieldTranslation, field.TypeString, value)
		_node.Translation = value
	}
	if value, ok := _c.mutation.TargetPositionStart(); ok {
		_spec.SetField(dictionaryexample.FieldTargetPositionStart, field.TypeInt, value)
		_node.TargetPositionStart = &value
	}
	if value, ok := _c.mutation.TargetPositionEnd(); ok {
		_spec.SetField(dictionaryexample.FieldTargetPositionEnd, field.TypeInt, value)
		_node.TargetPositionEnd = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dictionaryexample.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DictionaryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dictionaryexample.DictionaryTable,
			Columns: []string{dictionaryexample.DictionaryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.dictionary_dictionary_examples = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DictionaryExampleCreateBulk is the builder for creating many DictionaryExample entities in bulk.
type DictionaryExampleCreateBulk struct {
	config
	err      error
	builders []*DictionaryExampleCreate
}

// Save creates the DictionaryExample entities in the database.
func (_c *DictionaryExampleCreateBulk) Save(ctx context.Context) ([]*DictionaryExample, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DictionaryExample, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DictionaryExampleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DictionaryExampleCreateBulk) SaveX(ctx context.Context) []*DictionaryExample {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictionaryExampleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictionaryExampleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
