// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/fcmtoken"
	"github.com/nimyab/nim2book-back/ent/user"
)

// FcmToken is the model entity for the FcmToken schema.
type FcmToken struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FcmTokenQuery when eager-loading is set.
	Edges           FcmTokenEdges `json:"edges"`
	user_fcm_tokens *uuid.UUID
	selectValues    sql.SelectValues
}

// FcmTokenEdges holds the relations/edges for other nodes in the graph.
type FcmTokenEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FcmTokenEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FcmToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case fcmtoken.FieldToken:
			values[i] = new(sql.NullString)
		case fcmtoken.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case fcmtoken.FieldID:
			values[i] = new(uuid.UUID)
		case fcmtoken.ForeignKeys[0]: // user_fcm_tokens
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FcmToken fields.
func (_m *FcmToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case fcmtoken.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case fcmtoken.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case fcmtoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case fcmtoken.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_fcm_tokens", values[i])
			} else if value.Valid {
				_m.user_fcm_tokens = new(uuid.UUID)
				*_m.user_fcm_tokens = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FcmToken.
// This includes values selected through modifiers, order, etc.
func (_m *FcmToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the FcmToken entity.
func (_m *FcmToken) QueryUser() *UserQuery {
	return NewFcmTokenClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this FcmToken.
// Note that you need to call FcmToken.Unwrap() before calling this method if this FcmToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FcmToken) Update() *FcmTokenUpdateOne {
	return NewFcmTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FcmToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FcmToken) Unwrap() *FcmToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FcmToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FcmToken) String() string {
	var builder strings.Builder
	builder.WriteString("FcmToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// FcmTokens is a parsable slice of FcmToken.
type FcmTokens []*FcmToken
