// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/book"
	"github.com/nimyab/nim2book-back/ent/genre"
	"github.com/nimyab/nim2book-back/ent/personalbook"
	"github.com/nimyab/nim2book-back/ent/predicate"
)

// GenreUpdate is the builder for updating Genre entities.
type GenreUpdate struct {
	config
	hooks    []Hook
	mutation *GenreMutation
}

// Where appends a list predicates to the GenreUpdate builder.
func (_u *GenreUpdate) Where(ps ...predicate.Genre) *GenreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (_u *GenreUpdate) AddBookIDs(ids ...uuid.UUID) *GenreUpdate {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBooks adds the "books" edges to the Book entity.
func (_u *GenreUpdate) AddBooks(v ...*Book) *GenreUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// AddPersonalBookIDs adds the "personal_books" edge to the PersonalBook entity by IDs.
func (_u *GenreUpdate) AddPersonalBookIDs(ids ...uuid.UUID) *GenreUpdate {
	_u.mutation.AddPersonalBookIDs(ids...)
	return _u
}

// AddPersonalBooks adds the "personal_books" edges to the PersonalBook entity.
func (_u *GenreUpdate) AddPersonalBooks(v ...*PersonalBook) *GenreUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPersonalBookIDs(ids...)
}

// Mutation returns the GenreMutation object of the builder.
func (_u *GenreUpdate) Mutation() *GenreMutation {
	return _u.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (_u *GenreUpdate) ClearBooks() *GenreUpdate {
	_u.mutation.ClearBooks()
	return _u
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (_u *GenreUpdate) RemoveBookIDs(ids ...uuid.UUID) *GenreUpdate {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBooks removes "books" edges to Book entities.
func (_u *GenreUpdate) RemoveBooks(v ...*Book) *GenreUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// ClearPersonalBooks clears all "personal_books" edges to the PersonalBook entity.
func (_u *GenreUpdate) ClearPersonalBooks() *GenreUpdate {
	_u.mutation.ClearPersonalBooks()
	return _u
}

// RemovePersonalBookIDs removes the "personal_books" edge to PersonalBook entities by IDs.
func (_u *GenreUpdate) RemovePersonalBookIDs(ids ...uuid.UUID) *GenreUpdate {
	_u.mutation.RemovePersonalBookIDs(ids...)
	return _u
}

// RemovePersonalBooks removes "personal_books" edges to PersonalBook entities.
func (_u *GenreUpdate) RemovePersonalBooks(v ...*PersonalBook) *GenreUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePersonalBookIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GenreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GenreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GenreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(genre.Table, genre.Columns, sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.BooksTable,
			Columns: genre.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBooksIDs(); len(nodes) > 0 && !_u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.BooksTable,
			Columns: genre.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.BooksTable,
			Columns: genre.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PersonalBooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.PersonalBooksTable,
			Columns: genre.PersonalBooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPersonalBooksIDs(); len(nodes) > 0 && !_u.mutation.PersonalBooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.PersonalBooksTable,
			Columns: genre.PersonalBooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonalBooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.PersonalBooksTable,
			Columns: genre.PersonalBooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{genre.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GenreUpdateOne is the builder for updating a single Genre entity.
type GenreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GenreMutation
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (_u *GenreUpdateOne) AddBookIDs(ids ...uuid.UUID) *GenreUpdateOne {
	_u.mutation.AddBookIDs(ids...)
	return _u
}

// AddBooks adds the "books" edges to the Book entity.
func (_u *GenreUpdateOne) AddBooks(v ...*Book) *GenreUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBookIDs(ids...)
}

// AddPersonalBookIDs adds the "personal_books" edge to the PersonalBook entity by IDs.
func (_u *GenreUpdateOne) AddPersonalBookIDs(ids ...uuid.UUID) *GenreUpdateOne {
	_u.mutation.AddPersonalBookIDs(ids...)
	return _u
}

// AddPersonalBooks adds the "personal_books" edges to the PersonalBook entity.
func (_u *GenreUpdateOne) AddPersonalBooks(v ...*PersonalBook) *GenreUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPersonalBookIDs(ids...)
}

// Mutation returns the GenreMutation object of the builder.
func (_u *GenreUpdateOne) Mutation() *GenreMutation {
	return _u.mutation
}

// ClearBooks clears all "books" edges to the Book entity.
func (_u *GenreUpdateOne) ClearBooks() *GenreUpdateOne {
	_u.mutation.ClearBooks()
	return _u
}

// RemoveBookIDs removes the "books" edge to Book entities by IDs.
func (_u *GenreUpdateOne) RemoveBookIDs(ids ...uuid.UUID) *GenreUpdateOne {
	_u.mutation.RemoveBookIDs(ids...)
	return _u
}

// RemoveBooks removes "books" edges to Book entities.
func (_u *GenreUpdateOne) RemoveBooks(v ...*Book) *GenreUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBookIDs(ids...)
}

// ClearPersonalBooks clears all "personal_books" edges to the PersonalBook entity.
func (_u *GenreUpdateOne) ClearPersonalBooks() *GenreUpdateOne {
	_u.mutation.ClearPersonalBooks()
	return _u
}

// RemovePersonalBookIDs removes the "personal_books" edge to PersonalBook entities by IDs.
func (_u *GenreUpdateOne) RemovePersonalBookIDs(ids ...uuid.UUID) *GenreUpdateOne {
	_u.mutation.RemovePersonalBookIDs(ids...)
	return _u
}

// RemovePersonalBooks removes "personal_books" edges to PersonalBook entities.
func (_u *GenreUpdateOne) RemovePersonalBooks(v ...*PersonalBook) *GenreUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePersonalBookIDs(ids...)
}

// Where appends a list predicates to the GenreUpdate builder.
func (_u *GenreUpdateOne) Where(ps ...predicate.Genre) *GenreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GenreUpdateOne) Select(field string, fields ...string) *GenreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Genre entity.
func (_u *GenreUpdateOne) Save(ctx context.Context) (*Genre, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenreUpdateOne) SaveX(ctx context.Context) *Genre {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GenreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GenreUpdateOne) sqlSave(ctx context.Context) (_node *Genre, err error) {
	_spec := sqlgraph.NewUpdateSpec(genre.Table, genre.Columns, sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Genre.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, genre.FieldID)
		for _, f := range fields {
			if !genre.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != genre.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.BooksTable,
			Columns: genre.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBooksIDs(); len(nodes) > 0 && !_u.mutation.BooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.BooksTable,
			Columns: genre.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.BooksTable,
			Columns: genre.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PersonalBooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.PersonalBooksTable,
			Columns: genre.PersonalBooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPersonalBooksIDs(); len(nodes) > 0 && !_u.mutation.PersonalBooksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.PersonalBooksTable,
			Columns: genre.PersonalBooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonalBooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   genre.PersonalBooksTable,
			Columns: genre.PersonalBooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Genre{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{genre.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
