// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nimyab/nim2book-back/ent/personalbook"
	"github.com/nimyab/nim2book-back/ent/predicate"
)

// PersonalBookDelete is the builder for deleting a PersonalBook entity.
type PersonalBookDelete struct {
	config
	hooks    []Hook
	mutation *PersonalBookMutation
}

// Where appends a list predicates to the PersonalBookDelete builder.
func (_d *PersonalBookDelete) Where(ps ...predicate.PersonalBook) *PersonalBookDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PersonalBookDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PersonalBookDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PersonalBookDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(personalbook.Table, sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PersonalBookDeleteOne is the builder for deleting a single PersonalBook entity.
type PersonalBookDeleteOne struct {
	_d *PersonalBookDelete
}

// Where appends a list predicates to the PersonalBookDelete builder.
func (_d *PersonalBookDeleteOne) Where(ps ...predicate.PersonalBook) *PersonalBookDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PersonalBookDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{personalbook.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PersonalBookDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
