// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/author"
	"github.com/nimyab/nim2book-back/ent/genre"
	"github.com/nimyab/nim2book-back/ent/personalbook"
	"github.com/nimyab/nim2book-back/ent/personalbookchapter"
	"github.com/nimyab/nim2book-back/ent/user"
)

// PersonalBookCreate is the builder for creating a PersonalBook entity.
type PersonalBookCreate struct {
	config
	mutation *PersonalBookMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *PersonalBookCreate) SetTitle(v string) *PersonalBookCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetCoverURL sets the "cover_url" field.
func (_c *PersonalBookCreate) SetCoverURL(v string) *PersonalBookCreate {
	_c.mutation.SetCoverURL(v)
	return _c
}

// SetOriginalLang sets the "original_lang" field.
func (_c *PersonalBookCreate) SetOriginalLang(v string) *PersonalBookCreate {
	_c.mutation.SetOriginalLang(v)
	return _c
}

// SetNillableOriginalLang sets the "original_lang" field if the given value is not nil.
func (_c *PersonalBookCreate) SetNillableOriginalLang(v *string) *PersonalBookCreate {
	if v != nil {
		_c.SetOriginalLang(*v)
	}
	return _c
}

// SetTranslatedLang sets the "translated_lang" field.
func (_c *PersonalBookCreate) SetTranslatedLang(v string) *PersonalBookCreate {
	_c.mutation.SetTranslatedLang(v)
	return _c
}

// SetNillableTranslatedLang sets the "translated_lang" field if the given value is not nil.
func (_c *PersonalBookCreate) SetNillableTranslatedLang(v *string) *PersonalBookCreate {
	if v != nil {
		_c.SetTranslatedLang(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PersonalBookCreate) SetCreatedAt(v time.Time) *PersonalBookCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PersonalBookCreate) SetNillableCreatedAt(v *time.Time) *PersonalBookCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PersonalBookCreate) SetID(v uuid.UUID) *PersonalBookCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PersonalBookCreate) SetNillableID(v *uuid.UUID) *PersonalBookCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *PersonalBookCreate) SetUserID(id uuid.UUID) *PersonalBookCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *PersonalBookCreate) SetNillableUserID(id *uuid.UUID) *PersonalBookCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PersonalBookCreate) SetUser(v *User) *PersonalBookCreate {
	return _c.SetUserID(v.ID)
}

// SetAuthorID sets the "author" edge to the Author entity by ID.
func (_c *PersonalBookCreate) SetAuthorID(id uuid.UUID) *PersonalBookCreate {
	_c.mutation.SetAuthorID(id)
	return _c
}

// SetNillableAuthorID sets the "author" edge to the Author entity by ID if the given value is not nil.
func (_c *PersonalBookCreate) SetNillableAuthorID(id *uuid.UUID) *PersonalBookCreate {
	if id != nil {
		_c = _c.SetAuthorID(*id)
	}
	return _c
}

// SetAuthor sets the "author" edge to the Author entity.
func (_c *PersonalBookCreate) SetAuthor(v *Author) *PersonalBookCreate {
	return _c.SetAuthorID(v.ID)
}

// AddGenreIDs adds the "genres" edge to the Genre entity by IDs.
func (_c *PersonalBookCreate) AddGenreIDs(ids ...uuid.UUID) *PersonalBookCreate {
	_c.mutation.AddGenreIDs(ids...)
	return _c
}

// AddGenres adds the "genres" edges to the Genre entity.
func (_c *PersonalBookCreate) AddGenres(v ...*Genre) *PersonalBookCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddGenreIDs(ids...)
}

// AddPersonalBookChapterIDs adds the "personal_book_chapters" edge to the PersonalBookChapter entity by IDs.
func (_c *PersonalBookCreate) AddPersonalBookChapterIDs(ids ...uuid.UUID) *PersonalBookCreate {
	_c.mutation.AddPersonalBookChapterIDs(ids...)
	return _c
}

// AddPersonalBookChapters adds the "personal_book_chapters" edges to the PersonalBookChapter entity.
func (_c *PersonalBookCreate) AddPersonalBookChapters(v ...*PersonalBookChapter) *PersonalBookCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPersonalBookChapterIDs(ids...)
}

// Mutation returns the PersonalBookMutation object of the builder.
func (_c *PersonalBookCreate) Mutation() *PersonalBookMutation {
	return _c.mutation
}

// Save creates the PersonalBook in the database.
func (_c *PersonalBookCreate) Save(ctx context.Context) (*PersonalBook, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PersonalBookCreate) SaveX(ctx context.Context) *PersonalBook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonalBookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonalBookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PersonalBookCreate) defaults() {
	if _, ok := _c.mutation.OriginalLang(); !ok {
		v := personalbook.DefaultOriginalLang
		_c.mutation.SetOriginalLang(v)
	}
	if _, ok := _c.mutation.TranslatedLang(); !ok {
		v := personalbook.DefaultTranslatedLang
		_c.mutation.SetTranslatedLang(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := personalbook.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := personalbook.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PersonalBookCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "PersonalBook.title"`)}
	}
	if _, ok := _c.mutation.CoverURL(); !ok {
		return &ValidationError{Name: "cover_url", err: errors.New(`ent: missing required field "PersonalBook.cover_url"`)}
	}
	if _, ok := _c.mutation.OriginalLang(); !ok {
		return &ValidationError{Name: "original_lang", err: errors.New(`ent: missing required field "PersonalBook.original_lang"`)}
	}
	if _, ok := _c.mutation.TranslatedLang(); !ok {
		return &ValidationError{Name: "translated_lang", err: errors.New(`ent: missing required field "PersonalBook.translated_lang"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PersonalBook.created_at"`)}
	}
	return nil
}

func (_c *PersonalBookCreate) sqlSave(ctx context.Context) (*PersonalBook, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PersonalBookCreate) createSpec() (*PersonalBook, *sqlgraph.CreateSpec) {
	var (
		_node = &PersonalBook{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(personalbook.Table, sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(personalbook.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.CoverURL(); ok {
		_spec.SetField(personalbook.FieldCoverURL, field.TypeString, value)
		_node.CoverURL = value
	}
	if value, ok := _c.mutation.OriginalLang(); ok {
		_spec.SetField(personalbook.FieldOriginalLang, field.TypeString, value)
		_node.OriginalLang = value
	}
	if value, ok := _c.mutation.TranslatedLang(); ok {
		_spec.SetField(personalbook.FieldTranslatedLang, field.TypeString, value)
		_node.TranslatedLang = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(personalbook.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.UserTable,
			Columns: []string{personalbook.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_personal_books = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.AuthorTable,
			Columns: []string{personalbook.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.author_personal_books = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GenresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personalbook.GenresTable,
			Columns: personalbook.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PersonalBookChaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   personalbook.PersonalBookChaptersTable,
			Columns: []string{personalbook.PersonalBookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbookchapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PersonalBookCreateBulk is the builder for creating many PersonalBook entities in bulk.
type PersonalBookCreateBulk struct {
	config
	err      error
	builders []*PersonalBookCreate
}

// Save creates the PersonalBook entities in the database.
func (_c *PersonalBookCreateBulk) Save(ctx context.Context) ([]*PersonalBook, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PersonalBook, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PersonalBookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PersonalBookCreateBulk) SaveX(ctx context.Context) []*PersonalBook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PersonalBookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PersonalBookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
