// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nimyab/nim2book-back/ent/personalbookchapter"
	"github.com/nimyab/nim2book-back/ent/predicate"
)

// PersonalBookChapterDelete is the builder for deleting a PersonalBookChapter entity.
type PersonalBookChapterDelete struct {
	config
	hooks    []Hook
	mutation *PersonalBookChapterMutation
}

// Where appends a list predicates to the PersonalBookChapterDelete builder.
func (_d *PersonalBookChapterDelete) Where(ps ...predicate.PersonalBookChapter) *PersonalBookChapterDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PersonalBookChapterDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PersonalBookChapterDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PersonalBookChapterDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(personalbookchapter.Table, sqlgraph.NewFieldSpec(personalbookchapter.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PersonalBookChapterDeleteOne is the builder for deleting a single PersonalBookChapter entity.
type PersonalBookChapterDeleteOne struct {
	_d *PersonalBookChapterDelete
}

// Where appends a list predicates to the PersonalBookChapterDelete builder.
func (_d *PersonalBookChapterDeleteOne) Where(ps ...predicate.PersonalBookChapter) *PersonalBookChapterDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PersonalBookChapterDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{personalbookchapter.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PersonalBookChapterDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
