// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/author"
	"github.com/nimyab/nim2book-back/ent/personalbook"
	"github.com/nimyab/nim2book-back/ent/user"
)

// PersonalBook is the model entity for the PersonalBook schema.
type PersonalBook struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// CoverURL holds the value of the "cover_url" field.
	CoverURL *string `json:"cover_url,omitempty"`
	// OriginalLang holds the value of the "original_lang" field.
	OriginalLang string `json:"original_lang,omitempty"`
	// TranslatedLang holds the value of the "translated_lang" field.
	TranslatedLang string `json:"translated_lang,omitempty"`
	// ProcessStatus holds the value of the "process_status" field.
	ProcessStatus personalbook.ProcessStatus `json:"process_status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PersonalBookQuery when eager-loading is set.
	Edges                 PersonalBookEdges `json:"edges"`
	author_personal_books *uuid.UUID
	user_personal_books   *uuid.UUID
	selectValues          sql.SelectValues
}

// PersonalBookEdges holds the relations/edges for other nodes in the graph.
type PersonalBookEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Author holds the value of the author edge.
	Author *Author `json:"author,omitempty"`
	// Genres holds the value of the genres edge.
	Genres []*Genre `json:"genres,omitempty"`
	// PersonalBookChapters holds the value of the personal_book_chapters edge.
	PersonalBookChapters []*PersonalBookChapter `json:"personal_book_chapters,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PersonalBookEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AuthorOrErr returns the Author value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PersonalBookEdges) AuthorOrErr() (*Author, error) {
	if e.Author != nil {
		return e.Author, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: author.Label}
	}
	return nil, &NotLoadedError{edge: "author"}
}

// GenresOrErr returns the Genres value or an error if the edge
// was not loaded in eager-loading.
func (e PersonalBookEdges) GenresOrErr() ([]*Genre, error) {
	if e.loadedTypes[2] {
		return e.Genres, nil
	}
	return nil, &NotLoadedError{edge: "genres"}
}

// PersonalBookChaptersOrErr returns the PersonalBookChapters value or an error if the edge
// was not loaded in eager-loading.
func (e PersonalBookEdges) PersonalBookChaptersOrErr() ([]*PersonalBookChapter, error) {
	if e.loadedTypes[3] {
		return e.PersonalBookChapters, nil
	}
	return nil, &NotLoadedError{edge: "personal_book_chapters"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PersonalBook) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case personalbook.FieldTitle, personalbook.FieldCoverURL, personalbook.FieldOriginalLang, personalbook.FieldTranslatedLang, personalbook.FieldProcessStatus:
			values[i] = new(sql.NullString)
		case personalbook.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case personalbook.FieldID:
			values[i] = new(uuid.UUID)
		case personalbook.ForeignKeys[0]: // author_personal_books
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case personalbook.ForeignKeys[1]: // user_personal_books
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PersonalBook fields.
func (_m *PersonalBook) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case personalbook.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case personalbook.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case personalbook.FieldCoverURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover_url", values[i])
			} else if value.Valid {
				_m.CoverURL = new(string)
				*_m.CoverURL = value.String
			}
		case personalbook.FieldOriginalLang:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_lang", values[i])
			} else if value.Valid {
				_m.OriginalLang = value.String
			}
		case personalbook.FieldTranslatedLang:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field translated_lang", values[i])
			} else if value.Valid {
				_m.TranslatedLang = value.String
			}
		case personalbook.FieldProcessStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field process_status", values[i])
			} else if value.Valid {
				_m.ProcessStatus = personalbook.ProcessStatus(value.String)
			}
		case personalbook.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case personalbook.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field author_personal_books", values[i])
			} else if value.Valid {
				_m.author_personal_books = new(uuid.UUID)
				*_m.author_personal_books = *value.S.(*uuid.UUID)
			}
		case personalbook.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_personal_books", values[i])
			} else if value.Valid {
				_m.user_personal_books = new(uuid.UUID)
				*_m.user_personal_books = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PersonalBook.
// This includes values selected through modifiers, order, etc.
func (_m *PersonalBook) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PersonalBook entity.
func (_m *PersonalBook) QueryUser() *UserQuery {
	return NewPersonalBookClient(_m.config).QueryUser(_m)
}

// QueryAuthor queries the "author" edge of the PersonalBook entity.
func (_m *PersonalBook) QueryAuthor() *AuthorQuery {
	return NewPersonalBookClient(_m.config).QueryAuthor(_m)
}

// QueryGenres queries the "genres" edge of the PersonalBook entity.
func (_m *PersonalBook) QueryGenres() *GenreQuery {
	return NewPersonalBookClient(_m.config).QueryGenres(_m)
}

// QueryPersonalBookChapters queries the "personal_book_chapters" edge of the PersonalBook entity.
func (_m *PersonalBook) QueryPersonalBookChapters() *PersonalBookChapterQuery {
	return NewPersonalBookClient(_m.config).QueryPersonalBookChapters(_m)
}

// Update returns a builder for updating this PersonalBook.
// Note that you need to call PersonalBook.Unwrap() before calling this method if this PersonalBook
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PersonalBook) Update() *PersonalBookUpdateOne {
	return NewPersonalBookClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PersonalBook entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PersonalBook) Unwrap() *PersonalBook {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PersonalBook is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PersonalBook) String() string {
	var builder strings.Builder
	builder.WriteString("PersonalBook(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.CoverURL; v != nil {
		builder.WriteString("cover_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("original_lang=")
	builder.WriteString(_m.OriginalLang)
	builder.WriteString(", ")
	builder.WriteString("translated_lang=")
	builder.WriteString(_m.TranslatedLang)
	builder.WriteString(", ")
	builder.WriteString("process_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProcessStatus))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PersonalBooks is a parsable slice of PersonalBook.
type PersonalBooks []*PersonalBook
