// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/author"
	"github.com/nimyab/nim2book-back/ent/genre"
	"github.com/nimyab/nim2book-back/ent/personalbook"
	"github.com/nimyab/nim2book-back/ent/personalbookchapter"
	"github.com/nimyab/nim2book-back/ent/predicate"
	"github.com/nimyab/nim2book-back/ent/user"
)

// PersonalBookUpdate is the builder for updating PersonalBook entities.
type PersonalBookUpdate struct {
	config
	hooks    []Hook
	mutation *PersonalBookMutation
}

// Where appends a list predicates to the PersonalBookUpdate builder.
func (_u *PersonalBookUpdate) Where(ps ...predicate.PersonalBook) *PersonalBookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCoverURL sets the "cover_url" field.
func (_u *PersonalBookUpdate) SetCoverURL(v string) *PersonalBookUpdate {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *PersonalBookUpdate) SetNillableCoverURL(v *string) *PersonalBookUpdate {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// SetOriginalLang sets the "original_lang" field.
func (_u *PersonalBookUpdate) SetOriginalLang(v string) *PersonalBookUpdate {
	_u.mutation.SetOriginalLang(v)
	return _u
}

// SetNillableOriginalLang sets the "original_lang" field if the given value is not nil.
func (_u *PersonalBookUpdate) SetNillableOriginalLang(v *string) *PersonalBookUpdate {
	if v != nil {
		_u.SetOriginalLang(*v)
	}
	return _u
}

// SetTranslatedLang sets the "translated_lang" field.
func (_u *PersonalBookUpdate) SetTranslatedLang(v string) *PersonalBookUpdate {
	_u.mutation.SetTranslatedLang(v)
	return _u
}

// SetNillableTranslatedLang sets the "translated_lang" field if the given value is not nil.
func (_u *PersonalBookUpdate) SetNillableTranslatedLang(v *string) *PersonalBookUpdate {
	if v != nil {
		_u.SetTranslatedLang(*v)
	}
	return _u
}

// SetProcessStatus sets the "process_status" field.
func (_u *PersonalBookUpdate) SetProcessStatus(v personalbook.ProcessStatus) *PersonalBookUpdate {
	_u.mutation.SetProcessStatus(v)
	return _u
}

// SetNillableProcessStatus sets the "process_status" field if the given value is not nil.
func (_u *PersonalBookUpdate) SetNillableProcessStatus(v *personalbook.ProcessStatus) *PersonalBookUpdate {
	if v != nil {
		_u.SetProcessStatus(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PersonalBookUpdate) SetUserID(id uuid.UUID) *PersonalBookUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *PersonalBookUpdate) SetNillableUserID(id *uuid.UUID) *PersonalBookUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PersonalBookUpdate) SetUser(v *User) *PersonalBookUpdate {
	return _u.SetUserID(v.ID)
}

// SetAuthorID sets the "author" edge to the Author entity by ID.
func (_u *PersonalBookUpdate) SetAuthorID(id uuid.UUID) *PersonalBookUpdate {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetNillableAuthorID sets the "author" edge to the Author entity by ID if the given value is not nil.
func (_u *PersonalBookUpdate) SetNillableAuthorID(id *uuid.UUID) *PersonalBookUpdate {
	if id != nil {
		_u = _u.SetAuthorID(*id)
	}
	return _u
}

// SetAuthor sets the "author" edge to the Author entity.
func (_u *PersonalBookUpdate) SetAuthor(v *Author) *PersonalBookUpdate {
	return _u.SetAuthorID(v.ID)
}

// AddGenreIDs adds the "genres" edge to the Genre entity by IDs.
func (_u *PersonalBookUpdate) AddGenreIDs(ids ...uuid.UUID) *PersonalBookUpdate {
	_u.mutation.AddGenreIDs(ids...)
	return _u
}

// AddGenres adds the "genres" edges to the Genre entity.
func (_u *PersonalBookUpdate) AddGenres(v ...*Genre) *PersonalBookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGenreIDs(ids...)
}

// AddPersonalBookChapterIDs adds the "personal_book_chapters" edge to the PersonalBookChapter entity by IDs.
func (_u *PersonalBookUpdate) AddPersonalBookChapterIDs(ids ...uuid.UUID) *PersonalBookUpdate {
	_u.mutation.AddPersonalBookChapterIDs(ids...)
	return _u
}

// AddPersonalBookChapters adds the "personal_book_chapters" edges to the PersonalBookChapter entity.
func (_u *PersonalBookUpdate) AddPersonalBookChapters(v ...*PersonalBookChapter) *PersonalBookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPersonalBookChapterIDs(ids...)
}

// Mutation returns the PersonalBookMutation object of the builder.
func (_u *PersonalBookUpdate) Mutation() *PersonalBookMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PersonalBookUpdate) ClearUser() *PersonalBookUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAuthor clears the "author" edge to the Author entity.
func (_u *PersonalBookUpdate) ClearAuthor() *PersonalBookUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearGenres clears all "genres" edges to the Genre entity.
func (_u *PersonalBookUpdate) ClearGenres() *PersonalBookUpdate {
	_u.mutation.ClearGenres()
	return _u
}

// RemoveGenreIDs removes the "genres" edge to Genre entities by IDs.
func (_u *PersonalBookUpdate) RemoveGenreIDs(ids ...uuid.UUID) *PersonalBookUpdate {
	_u.mutation.RemoveGenreIDs(ids...)
	return _u
}

// RemoveGenres removes "genres" edges to Genre entities.
func (_u *PersonalBookUpdate) RemoveGenres(v ...*Genre) *PersonalBookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGenreIDs(ids...)
}

// ClearPersonalBookChapters clears all "personal_book_chapters" edges to the PersonalBookChapter entity.
func (_u *PersonalBookUpdate) ClearPersonalBookChapters() *PersonalBookUpdate {
	_u.mutation.ClearPersonalBookChapters()
	return _u
}

// RemovePersonalBookChapterIDs removes the "personal_book_chapters" edge to PersonalBookChapter entities by IDs.
func (_u *PersonalBookUpdate) RemovePersonalBookChapterIDs(ids ...uuid.UUID) *PersonalBookUpdate {
	_u.mutation.RemovePersonalBookChapterIDs(ids...)
	return _u
}

// RemovePersonalBookChapters removes "personal_book_chapters" edges to PersonalBookChapter entities.
func (_u *PersonalBookUpdate) RemovePersonalBookChapters(v ...*PersonalBookChapter) *PersonalBookUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePersonalBookChapterIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PersonalBookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonalBookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PersonalBookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonalBookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonalBookUpdate) check() error {
	if v, ok := _u.mutation.ProcessStatus(); ok {
		if err := personalbook.ProcessStatusValidator(v); err != nil {
			return &ValidationError{Name: "process_status", err: fmt.Errorf(`ent: validator failed for field "PersonalBook.process_status": %w`, err)}
		}
	}
	return nil
}

func (_u *PersonalBookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personalbook.Table, personalbook.Columns, sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(personalbook.FieldCoverURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalLang(); ok {
		_spec.SetField(personalbook.FieldOriginalLang, field.TypeString, value)
	}
	if value, ok := _u.mutation.TranslatedLang(); ok {
		_spec.SetField(personalbook.FieldTranslatedLang, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessStatus(); ok {
		_spec.SetField(personalbook.FieldProcessStatus, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.UserTable,
			Columns: []string{personalbook.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.UserTable,
			Columns: []string{personalbook.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.AuthorTable,
			Columns: []string{personalbook.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.AuthorTable,
			Columns: []string{personalbook.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personalbook.GenresTable,
			Columns: personalbook.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGenresIDs(); len(nodes) > 0 && !_u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personalbook.GenresTable,
			Columns: personalbook.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GenresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personalbook.GenresTable,
			Columns: personalbook.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PersonalBookChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   personalbook.PersonalBookChaptersTable,
			Columns: []string{personalbook.PersonalBookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbookchapter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPersonalBookChaptersIDs(); len(nodes) > 0 && !_u.mutation.PersonalBookChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   personalbook.PersonalBookChaptersTable,
			Columns: []string{personalbook.PersonalBookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbookchapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonalBookChaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   personalbook.PersonalBookChaptersTable,
			Columns: []string{personalbook.PersonalBookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbookchapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personalbook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PersonalBookUpdateOne is the builder for updating a single PersonalBook entity.
type PersonalBookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonalBookMutation
}

// SetCoverURL sets the "cover_url" field.
func (_u *PersonalBookUpdateOne) SetCoverURL(v string) *PersonalBookUpdateOne {
	_u.mutation.SetCoverURL(v)
	return _u
}

// SetNillableCoverURL sets the "cover_url" field if the given value is not nil.
func (_u *PersonalBookUpdateOne) SetNillableCoverURL(v *string) *PersonalBookUpdateOne {
	if v != nil {
		_u.SetCoverURL(*v)
	}
	return _u
}

// SetOriginalLang sets the "original_lang" field.
func (_u *PersonalBookUpdateOne) SetOriginalLang(v string) *PersonalBookUpdateOne {
	_u.mutation.SetOriginalLang(v)
	return _u
}

// SetNillableOriginalLang sets the "original_lang" field if the given value is not nil.
func (_u *PersonalBookUpdateOne) SetNillableOriginalLang(v *string) *PersonalBookUpdateOne {
	if v != nil {
		_u.SetOriginalLang(*v)
	}
	return _u
}

// SetTranslatedLang sets the "translated_lang" field.
func (_u *PersonalBookUpdateOne) SetTranslatedLang(v string) *PersonalBookUpdateOne {
	_u.mutation.SetTranslatedLang(v)
	return _u
}

// SetNillableTranslatedLang sets the "translated_lang" field if the given value is not nil.
func (_u *PersonalBookUpdateOne) SetNillableTranslatedLang(v *string) *PersonalBookUpdateOne {
	if v != nil {
		_u.SetTranslatedLang(*v)
	}
	return _u
}

// SetProcessStatus sets the "process_status" field.
func (_u *PersonalBookUpdateOne) SetProcessStatus(v personalbook.ProcessStatus) *PersonalBookUpdateOne {
	_u.mutation.SetProcessStatus(v)
	return _u
}

// SetNillableProcessStatus sets the "process_status" field if the given value is not nil.
func (_u *PersonalBookUpdateOne) SetNillableProcessStatus(v *personalbook.ProcessStatus) *PersonalBookUpdateOne {
	if v != nil {
		_u.SetProcessStatus(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PersonalBookUpdateOne) SetUserID(id uuid.UUID) *PersonalBookUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *PersonalBookUpdateOne) SetNillableUserID(id *uuid.UUID) *PersonalBookUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PersonalBookUpdateOne) SetUser(v *User) *PersonalBookUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAuthorID sets the "author" edge to the Author entity by ID.
func (_u *PersonalBookUpdateOne) SetAuthorID(id uuid.UUID) *PersonalBookUpdateOne {
	_u.mutation.SetAuthorID(id)
	return _u
}

// SetNillableAuthorID sets the "author" edge to the Author entity by ID if the given value is not nil.
func (_u *PersonalBookUpdateOne) SetNillableAuthorID(id *uuid.UUID) *PersonalBookUpdateOne {
	if id != nil {
		_u = _u.SetAuthorID(*id)
	}
	return _u
}

// SetAuthor sets the "author" edge to the Author entity.
func (_u *PersonalBookUpdateOne) SetAuthor(v *Author) *PersonalBookUpdateOne {
	return _u.SetAuthorID(v.ID)
}

// AddGenreIDs adds the "genres" edge to the Genre entity by IDs.
func (_u *PersonalBookUpdateOne) AddGenreIDs(ids ...uuid.UUID) *PersonalBookUpdateOne {
	_u.mutation.AddGenreIDs(ids...)
	return _u
}

// AddGenres adds the "genres" edges to the Genre entity.
func (_u *PersonalBookUpdateOne) AddGenres(v ...*Genre) *PersonalBookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGenreIDs(ids...)
}

// AddPersonalBookChapterIDs adds the "personal_book_chapters" edge to the PersonalBookChapter entity by IDs.
func (_u *PersonalBookUpdateOne) AddPersonalBookChapterIDs(ids ...uuid.UUID) *PersonalBookUpdateOne {
	_u.mutation.AddPersonalBookChapterIDs(ids...)
	return _u
}

// AddPersonalBookChapters adds the "personal_book_chapters" edges to the PersonalBookChapter entity.
func (_u *PersonalBookUpdateOne) AddPersonalBookChapters(v ...*PersonalBookChapter) *PersonalBookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPersonalBookChapterIDs(ids...)
}

// Mutation returns the PersonalBookMutation object of the builder.
func (_u *PersonalBookUpdateOne) Mutation() *PersonalBookMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PersonalBookUpdateOne) ClearUser() *PersonalBookUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAuthor clears the "author" edge to the Author entity.
func (_u *PersonalBookUpdateOne) ClearAuthor() *PersonalBookUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// ClearGenres clears all "genres" edges to the Genre entity.
func (_u *PersonalBookUpdateOne) ClearGenres() *PersonalBookUpdateOne {
	_u.mutation.ClearGenres()
	return _u
}

// RemoveGenreIDs removes the "genres" edge to Genre entities by IDs.
func (_u *PersonalBookUpdateOne) RemoveGenreIDs(ids ...uuid.UUID) *PersonalBookUpdateOne {
	_u.mutation.RemoveGenreIDs(ids...)
	return _u
}

// RemoveGenres removes "genres" edges to Genre entities.
func (_u *PersonalBookUpdateOne) RemoveGenres(v ...*Genre) *PersonalBookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGenreIDs(ids...)
}

// ClearPersonalBookChapters clears all "personal_book_chapters" edges to the PersonalBookChapter entity.
func (_u *PersonalBookUpdateOne) ClearPersonalBookChapters() *PersonalBookUpdateOne {
	_u.mutation.ClearPersonalBookChapters()
	return _u
}

// RemovePersonalBookChapterIDs removes the "personal_book_chapters" edge to PersonalBookChapter entities by IDs.
func (_u *PersonalBookUpdateOne) RemovePersonalBookChapterIDs(ids ...uuid.UUID) *PersonalBookUpdateOne {
	_u.mutation.RemovePersonalBookChapterIDs(ids...)
	return _u
}

// RemovePersonalBookChapters removes "personal_book_chapters" edges to PersonalBookChapter entities.
func (_u *PersonalBookUpdateOne) RemovePersonalBookChapters(v ...*PersonalBookChapter) *PersonalBookUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePersonalBookChapterIDs(ids...)
}

// Where appends a list predicates to the PersonalBookUpdate builder.
func (_u *PersonalBookUpdateOne) Where(ps ...predicate.PersonalBook) *PersonalBookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PersonalBookUpdateOne) Select(field string, fields ...string) *PersonalBookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PersonalBook entity.
func (_u *PersonalBookUpdateOne) Save(ctx context.Context) (*PersonalBook, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PersonalBookUpdateOne) SaveX(ctx context.Context) *PersonalBook {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PersonalBookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PersonalBookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PersonalBookUpdateOne) check() error {
	if v, ok := _u.mutation.ProcessStatus(); ok {
		if err := personalbook.ProcessStatusValidator(v); err != nil {
			return &ValidationError{Name: "process_status", err: fmt.Errorf(`ent: validator failed for field "PersonalBook.process_status": %w`, err)}
		}
	}
	return nil
}

func (_u *PersonalBookUpdateOne) sqlSave(ctx context.Context) (_node *PersonalBook, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(personalbook.Table, personalbook.Columns, sqlgraph.NewFieldSpec(personalbook.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PersonalBook.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, personalbook.FieldID)
		for _, f := range fields {
			if !personalbook.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != personalbook.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CoverURL(); ok {
		_spec.SetField(personalbook.FieldCoverURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.OriginalLang(); ok {
		_spec.SetField(personalbook.FieldOriginalLang, field.TypeString, value)
	}
	if value, ok := _u.mutation.TranslatedLang(); ok {
		_spec.SetField(personalbook.FieldTranslatedLang, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessStatus(); ok {
		_spec.SetField(personalbook.FieldProcessStatus, field.TypeEnum, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.UserTable,
			Columns: []string{personalbook.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.UserTable,
			Columns: []string{personalbook.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.AuthorTable,
			Columns: []string{personalbook.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalbook.AuthorTable,
			Columns: []string{personalbook.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(author.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personalbook.GenresTable,
			Columns: personalbook.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGenresIDs(); len(nodes) > 0 && !_u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personalbook.GenresTable,
			Columns: personalbook.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GenresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   personalbook.GenresTable,
			Columns: personalbook.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PersonalBookChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   personalbook.PersonalBookChaptersTable,
			Columns: []string{personalbook.PersonalBookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbookchapter.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPersonalBookChaptersIDs(); len(nodes) > 0 && !_u.mutation.PersonalBookChaptersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   personalbook.PersonalBookChaptersTable,
			Columns: []string{personalbook.PersonalBookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbookchapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonalBookChaptersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   personalbook.PersonalBookChaptersTable,
			Columns: []string{personalbook.PersonalBookChaptersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(personalbookchapter.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PersonalBook{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personalbook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
