// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/basicaccount"
	"github.com/nimyab/nim2book-back/ent/googleaccount"
	"github.com/nimyab/nim2book-back/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// IsVip holds the value of the "is_vip" field.
	IsVip bool `json:"is_vip,omitempty"`
	// IsAdmin holds the value of the "is_admin" field.
	IsAdmin bool `json:"is_admin,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// GoogleAccount holds the value of the google_account edge.
	GoogleAccount *GoogleAccount `json:"google_account,omitempty"`
	// BasicAccount holds the value of the basic_account edge.
	BasicAccount *BasicAccount `json:"basic_account,omitempty"`
	// PersonalBooks holds the value of the personal_books edge.
	PersonalBooks []*PersonalBook `json:"personal_books,omitempty"`
	// FcmTokens holds the value of the fcm_tokens edge.
	FcmTokens []*FcmToken `json:"fcm_tokens,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// GoogleAccountOrErr returns the GoogleAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) GoogleAccountOrErr() (*GoogleAccount, error) {
	if e.GoogleAccount != nil {
		return e.GoogleAccount, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: googleaccount.Label}
	}
	return nil, &NotLoadedError{edge: "google_account"}
}

// BasicAccountOrErr returns the BasicAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) BasicAccountOrErr() (*BasicAccount, error) {
	if e.BasicAccount != nil {
		return e.BasicAccount, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: basicaccount.Label}
	}
	return nil, &NotLoadedError{edge: "basic_account"}
}

// PersonalBooksOrErr returns the PersonalBooks value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) PersonalBooksOrErr() ([]*PersonalBook, error) {
	if e.loadedTypes[2] {
		return e.PersonalBooks, nil
	}
	return nil, &NotLoadedError{edge: "personal_books"}
}

// FcmTokensOrErr returns the FcmTokens value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) FcmTokensOrErr() ([]*FcmToken, error) {
	if e.loadedTypes[3] {
		return e.FcmTokens, nil
	}
	return nil, &NotLoadedError{edge: "fcm_tokens"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldMetadata:
			values[i] = new([]byte)
		case user.FieldIsVip, user.FieldIsAdmin:
			values[i] = new(sql.NullBool)
		case user.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case user.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case user.FieldIsVip:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_vip", values[i])
			} else if value.Valid {
				_m.IsVip = value.Bool
			}
		case user.FieldIsAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_admin", values[i])
			} else if value.Valid {
				_m.IsAdmin = value.Bool
			}
		case user.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGoogleAccount queries the "google_account" edge of the User entity.
func (_m *User) QueryGoogleAccount() *GoogleAccountQuery {
	return NewUserClient(_m.config).QueryGoogleAccount(_m)
}

// QueryBasicAccount queries the "basic_account" edge of the User entity.
func (_m *User) QueryBasicAccount() *BasicAccountQuery {
	return NewUserClient(_m.config).QueryBasicAccount(_m)
}

// QueryPersonalBooks queries the "personal_books" edge of the User entity.
func (_m *User) QueryPersonalBooks() *PersonalBookQuery {
	return NewUserClient(_m.config).QueryPersonalBooks(_m)
}

// QueryFcmTokens queries the "fcm_tokens" edge of the User entity.
func (_m *User) QueryFcmTokens() *FcmTokenQuery {
	return NewUserClient(_m.config).QueryFcmTokens(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("is_vip=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsVip))
	builder.WriteString(", ")
	builder.WriteString("is_admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAdmin))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
