// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package notification

import (
	"context"

	"firebase.google.com/go/v4/messaging"
	"github.com/nimyab/nim2book-back/internal/controller/websocket"
	"github.com/nimyab/nim2book-back/internal/domain"
	"github.com/nimyab/nim2book-back/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFcmTokenRepository creates a new instance of MockFcmTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFcmTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFcmTokenRepository {
	mock := &MockFcmTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFcmTokenRepository is an autogenerated mock type for the FcmTokenRepository type
type MockFcmTokenRepository struct {
	mock.Mock
}

type MockFcmTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFcmTokenRepository) EXPECT() *MockFcmTokenRepository_Expecter {
	return &MockFcmTokenRepository_Expecter{mock: &_m.Mock}
}

// DeleteByToken provides a mock function for the type MockFcmTokenRepository
func (_mock *MockFcmTokenRepository) DeleteByToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFcmTokenRepository_DeleteByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByToken'
type MockFcmTokenRepository_DeleteByToken_Call struct {
	*mock.Call
}

// DeleteByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockFcmTokenRepository_Expecter) DeleteByToken(ctx interface{}, token interface{}) *MockFcmTokenRepository_DeleteByToken_Call {
	return &MockFcmTokenRepository_DeleteByToken_Call{Call: _e.mock.On("DeleteByToken", ctx, token)}
}

func (_c *MockFcmTokenRepository_DeleteByToken_Call) Run(run func(ctx context.Context, token string)) *MockFcmTokenRepository_DeleteByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFcmTokenRepository_DeleteByToken_Call) Return(err error) *MockFcmTokenRepository_DeleteByToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFcmTokenRepository_DeleteByToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockFcmTokenRepository_DeleteByToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockFcmTokenRepository
func (_mock *MockFcmTokenRepository) ListByUserID(ctx context.Context, userID domain.ID, opts repository.QueryOptions) ([]*domain.FcmToken, error) {
	ret := _mock.Called(ctx, userID, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*domain.FcmToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, repository.QueryOptions) ([]*domain.FcmToken, error)); ok {
		return returnFunc(ctx, userID, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID, repository.QueryOptions) []*domain.FcmToken); ok {
		r0 = returnFunc(ctx, userID, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.FcmToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID, repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, userID, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFcmTokenRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockFcmTokenRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.ID
//   - opts repository.QueryOptions
func (_e *MockFcmTokenRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, opts interface{}) *MockFcmTokenRepository_ListByUserID_Call {
	return &MockFcmTokenRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, opts)}
}

func (_c *MockFcmTokenRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID domain.ID, opts repository.QueryOptions)) *MockFcmTokenRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		var arg2 repository.QueryOptions
		if args[2] != nil {
			arg2 = args[2].(repository.QueryOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFcmTokenRepository_ListByUserID_Call) Return(fcmTokens []*domain.FcmToken, err error) *MockFcmTokenRepository_ListByUserID_Call {
	_c.Call.Return(fcmTokens, err)
	return _c
}

func (_c *MockFcmTokenRepository_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID domain.ID, opts repository.QueryOptions) ([]*domain.FcmToken, error)) *MockFcmTokenRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessagingClient creates a new instance of MockMessagingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagingClient {
	mock := &MockMessagingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessagingClient is an autogenerated mock type for the MessagingClient type
type MockMessagingClient struct {
	mock.Mock
}

type MockMessagingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessagingClient) EXPECT() *MockMessagingClient_Expecter {
	return &MockMessagingClient_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockMessagingClient
func (_mock *MockMessagingClient) Send(ctx context.Context, message *messaging.Message) (string, error) {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messaging.Message) (string, error)); ok {
		return returnFunc(ctx, message)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *messaging.Message) string); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *messaging.Message) error); ok {
		r1 = returnFunc(ctx, message)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessagingClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMessagingClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - message *messaging.Message
func (_e *MockMessagingClient_Expecter) Send(ctx interface{}, message interface{}) *MockMessagingClient_Send_Call {
	return &MockMessagingClient_Send_Call{Call: _e.mock.On("Send", ctx, message)}
}

func (_c *MockMessagingClient_Send_Call) Run(run func(ctx context.Context, message *messaging.Message)) *MockMessagingClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *messaging.Message
		if args[1] != nil {
			arg1 = args[1].(*messaging.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessagingClient_Send_Call) Return(s string, err error) *MockMessagingClient_Send_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMessagingClient_Send_Call) RunAndReturn(run func(ctx context.Context, message *messaging.Message) (string, error)) *MockMessagingClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebsocketSender creates a new instance of MockWebsocketSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsocketSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsocketSender {
	mock := &MockWebsocketSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebsocketSender is an autogenerated mock type for the WebsocketSender type
type MockWebsocketSender struct {
	mock.Mock
}

type MockWebsocketSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebsocketSender) EXPECT() *MockWebsocketSender_Expecter {
	return &MockWebsocketSender_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function for the type MockWebsocketSender
func (_mock *MockWebsocketSender) SendMessage(userId domain.ID, msg *websocket.Message) {
	_mock.Called(userId, msg)
	return
}

// MockWebsocketSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockWebsocketSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - userId domain.ID
//   - msg *websocket.Message
func (_e *MockWebsocketSender_Expecter) SendMessage(userId interface{}, msg interface{}) *MockWebsocketSender_SendMessage_Call {
	return &MockWebsocketSender_SendMessage_Call{Call: _e.mock.On("SendMessage", userId, msg)}
}

func (_c *MockWebsocketSender_SendMessage_Call) Run(run func(userId domain.ID, msg *websocket.Message)) *MockWebsocketSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.ID
		if args[0] != nil {
			arg0 = args[0].(domain.ID)
		}
		var arg1 *websocket.Message
		if args[1] != nil {
			arg1 = args[1].(*websocket.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsocketSender_SendMessage_Call) Return() *MockWebsocketSender_SendMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsocketSender_SendMessage_Call) RunAndReturn(run func(userId domain.ID, msg *websocket.Message)) *MockWebsocketSender_SendMessage_Call {
	_c.Run(run)
	return _c
}
