// Code generated by ent, DO NOT EDIT.

package bookchapter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLTE(FieldID, id))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldOrder, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldTitle, v))
}

// TranslatedTitle applies equality check predicate on the "translated_title" field. It's identical to TranslatedTitleEQ.
func TranslatedTitle(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldTranslatedTitle, v))
}

// ContentURL applies equality check predicate on the "content_url" field. It's identical to ContentURLEQ.
func ContentURL(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldContentURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldCreatedAt, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLTE(FieldOrder, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldContainsFold(FieldTitle, v))
}

// TranslatedTitleEQ applies the EQ predicate on the "translated_title" field.
func TranslatedTitleEQ(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldTranslatedTitle, v))
}

// TranslatedTitleNEQ applies the NEQ predicate on the "translated_title" field.
func TranslatedTitleNEQ(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNEQ(FieldTranslatedTitle, v))
}

// TranslatedTitleIn applies the In predicate on the "translated_title" field.
func TranslatedTitleIn(vs ...string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldIn(FieldTranslatedTitle, vs...))
}

// TranslatedTitleNotIn applies the NotIn predicate on the "translated_title" field.
func TranslatedTitleNotIn(vs ...string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNotIn(FieldTranslatedTitle, vs...))
}

// TranslatedTitleGT applies the GT predicate on the "translated_title" field.
func TranslatedTitleGT(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGT(FieldTranslatedTitle, v))
}

// TranslatedTitleGTE applies the GTE predicate on the "translated_title" field.
func TranslatedTitleGTE(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGTE(FieldTranslatedTitle, v))
}

// TranslatedTitleLT applies the LT predicate on the "translated_title" field.
func TranslatedTitleLT(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLT(FieldTranslatedTitle, v))
}

// TranslatedTitleLTE applies the LTE predicate on the "translated_title" field.
func TranslatedTitleLTE(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLTE(FieldTranslatedTitle, v))
}

// TranslatedTitleContains applies the Contains predicate on the "translated_title" field.
func TranslatedTitleContains(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldContains(FieldTranslatedTitle, v))
}

// TranslatedTitleHasPrefix applies the HasPrefix predicate on the "translated_title" field.
func TranslatedTitleHasPrefix(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldHasPrefix(FieldTranslatedTitle, v))
}

// TranslatedTitleHasSuffix applies the HasSuffix predicate on the "translated_title" field.
func TranslatedTitleHasSuffix(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldHasSuffix(FieldTranslatedTitle, v))
}

// TranslatedTitleEqualFold applies the EqualFold predicate on the "translated_title" field.
func TranslatedTitleEqualFold(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEqualFold(FieldTranslatedTitle, v))
}

// TranslatedTitleContainsFold applies the ContainsFold predicate on the "translated_title" field.
func TranslatedTitleContainsFold(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldContainsFold(FieldTranslatedTitle, v))
}

// ContentURLEQ applies the EQ predicate on the "content_url" field.
func ContentURLEQ(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldContentURL, v))
}

// ContentURLNEQ applies the NEQ predicate on the "content_url" field.
func ContentURLNEQ(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNEQ(FieldContentURL, v))
}

// ContentURLIn applies the In predicate on the "content_url" field.
func ContentURLIn(vs ...string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldIn(FieldContentURL, vs...))
}

// ContentURLNotIn applies the NotIn predicate on the "content_url" field.
func ContentURLNotIn(vs ...string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNotIn(FieldContentURL, vs...))
}

// ContentURLGT applies the GT predicate on the "content_url" field.
func ContentURLGT(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGT(FieldContentURL, v))
}

// ContentURLGTE applies the GTE predicate on the "content_url" field.
func ContentURLGTE(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGTE(FieldContentURL, v))
}

// ContentURLLT applies the LT predicate on the "content_url" field.
func ContentURLLT(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLT(FieldContentURL, v))
}

// ContentURLLTE applies the LTE predicate on the "content_url" field.
func ContentURLLTE(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLTE(FieldContentURL, v))
}

// ContentURLContains applies the Contains predicate on the "content_url" field.
func ContentURLContains(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldContains(FieldContentURL, v))
}

// ContentURLHasPrefix applies the HasPrefix predicate on the "content_url" field.
func ContentURLHasPrefix(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldHasPrefix(FieldContentURL, v))
}

// ContentURLHasSuffix applies the HasSuffix predicate on the "content_url" field.
func ContentURLHasSuffix(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldHasSuffix(FieldContentURL, v))
}

// ContentURLEqualFold applies the EqualFold predicate on the "content_url" field.
func ContentURLEqualFold(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEqualFold(FieldContentURL, v))
}

// ContentURLContainsFold applies the ContainsFold predicate on the "content_url" field.
func ContentURLContainsFold(v string) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldContainsFold(FieldContentURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BookChapter {
	return predicate.BookChapter(sql.FieldLTE(FieldCreatedAt, v))
}

// HasBook applies the HasEdge predicate on the "book" edge.
func HasBook() predicate.BookChapter {
	return predicate.BookChapter(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BookTable, BookColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBookWith applies the HasEdge predicate on the "book" edge with a given conditions (other predicates).
func HasBookWith(preds ...predicate.Book) predicate.BookChapter {
	return predicate.BookChapter(func(s *sql.Selector) {
		step := newBookStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BookChapter) predicate.BookChapter {
	return predicate.BookChapter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BookChapter) predicate.BookChapter {
	return predicate.BookChapter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BookChapter) predicate.BookChapter {
	return predicate.BookChapter(sql.NotPredicates(p))
}
