// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package translate

import (
	"net/http"
	"net/url"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHTTPClient creates a new instance of MockHTTPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPClient {
	mock := &MockHTTPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHTTPClient is an autogenerated mock type for the HTTPClient type
type MockHTTPClient struct {
	mock.Mock
}

type MockHTTPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPClient) EXPECT() *MockHTTPClient_Expecter {
	return &MockHTTPClient_Expecter{mock: &_m.Mock}
}

// PostForm provides a mock function for the type MockHTTPClient
func (_mock *MockHTTPClient) PostForm(url1 string, data url.Values) (*http.Response, error) {
	ret := _mock.Called(url1, data)

	if len(ret) == 0 {
		panic("no return value specified for PostForm")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, url.Values) (*http.Response, error)); ok {
		return returnFunc(url1, data)
	}
	if returnFunc, ok := ret.Get(0).(func(string, url.Values) *http.Response); ok {
		r0 = returnFunc(url1, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, url.Values) error); ok {
		r1 = returnFunc(url1, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHTTPClient_PostForm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostForm'
type MockHTTPClient_PostForm_Call struct {
	*mock.Call
}

// PostForm is a helper method to define mock.On call
//   - url1 string
//   - data url.Values
func (_e *MockHTTPClient_Expecter) PostForm(url1 interface{}, data interface{}) *MockHTTPClient_PostForm_Call {
	return &MockHTTPClient_PostForm_Call{Call: _e.mock.On("PostForm", url1, data)}
}

func (_c *MockHTTPClient_PostForm_Call) Run(run func(url1 string, data url.Values)) *MockHTTPClient_PostForm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 url.Values
		if args[1] != nil {
			arg1 = args[1].(url.Values)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHTTPClient_PostForm_Call) Return(response *http.Response, err error) *MockHTTPClient_PostForm_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockHTTPClient_PostForm_Call) RunAndReturn(run func(url1 string, data url.Values) (*http.Response, error)) *MockHTTPClient_PostForm_Call {
	_c.Call.Return(run)
	return _c
}
