// Code generated by ent, DO NOT EDIT.

package basicaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/nimyab/nim2book-back/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldEmail, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldPasswordHash, v))
}

// IsVerified applies equality check predicate on the "is_verified" field. It's identical to IsVerifiedEQ.
func IsVerified(v bool) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldIsVerified, v))
}

// VerifyLink applies equality check predicate on the "verify_link" field. It's identical to VerifyLinkEQ.
func VerifyLink(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldVerifyLink, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldContainsFold(FieldPasswordHash, v))
}

// IsVerifiedEQ applies the EQ predicate on the "is_verified" field.
func IsVerifiedEQ(v bool) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldIsVerified, v))
}

// IsVerifiedNEQ applies the NEQ predicate on the "is_verified" field.
func IsVerifiedNEQ(v bool) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNEQ(FieldIsVerified, v))
}

// VerifyLinkEQ applies the EQ predicate on the "verify_link" field.
func VerifyLinkEQ(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldVerifyLink, v))
}

// VerifyLinkNEQ applies the NEQ predicate on the "verify_link" field.
func VerifyLinkNEQ(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNEQ(FieldVerifyLink, v))
}

// VerifyLinkIn applies the In predicate on the "verify_link" field.
func VerifyLinkIn(vs ...string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldIn(FieldVerifyLink, vs...))
}

// VerifyLinkNotIn applies the NotIn predicate on the "verify_link" field.
func VerifyLinkNotIn(vs ...string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNotIn(FieldVerifyLink, vs...))
}

// VerifyLinkGT applies the GT predicate on the "verify_link" field.
func VerifyLinkGT(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGT(FieldVerifyLink, v))
}

// VerifyLinkGTE applies the GTE predicate on the "verify_link" field.
func VerifyLinkGTE(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGTE(FieldVerifyLink, v))
}

// VerifyLinkLT applies the LT predicate on the "verify_link" field.
func VerifyLinkLT(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLT(FieldVerifyLink, v))
}

// VerifyLinkLTE applies the LTE predicate on the "verify_link" field.
func VerifyLinkLTE(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLTE(FieldVerifyLink, v))
}

// VerifyLinkContains applies the Contains predicate on the "verify_link" field.
func VerifyLinkContains(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldContains(FieldVerifyLink, v))
}

// VerifyLinkHasPrefix applies the HasPrefix predicate on the "verify_link" field.
func VerifyLinkHasPrefix(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldHasPrefix(FieldVerifyLink, v))
}

// VerifyLinkHasSuffix applies the HasSuffix predicate on the "verify_link" field.
func VerifyLinkHasSuffix(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldHasSuffix(FieldVerifyLink, v))
}

// VerifyLinkEqualFold applies the EqualFold predicate on the "verify_link" field.
func VerifyLinkEqualFold(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEqualFold(FieldVerifyLink, v))
}

// VerifyLinkContainsFold applies the ContainsFold predicate on the "verify_link" field.
func VerifyLinkContainsFold(v string) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldContainsFold(FieldVerifyLink, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BasicAccount {
	return predicate.BasicAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.BasicAccount {
	return predicate.BasicAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.BasicAccount {
	return predicate.BasicAccount(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BasicAccount) predicate.BasicAccount {
	return predicate.BasicAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BasicAccount) predicate.BasicAccount {
	return predicate.BasicAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BasicAccount) predicate.BasicAccount {
	return predicate.BasicAccount(sql.NotPredicates(p))
}
