basePath: /api/v1
definitions:
  domain.Book:
    properties:
      author:
        type: string
      chapterPaths:
        items:
          type: string
        type: array
      cover:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  domain.ChapterAlignNode:
    properties:
      content:
        items:
          $ref: '#/definitions/domain.ParagraphAlignNode'
        type: array
      id:
        type: string
      order:
        type: integer
      title:
        type: string
      translatedTitle:
        type: string
    type: object
  domain.Definition:
    properties:
      pos:
        type: string
      text:
        type: string
      tr:
        items:
          $ref: '#/definitions/domain.Translation'
        type: array
      ts:
        type: string
    required:
    - text
    - tr
    type: object
  domain.Example:
    properties:
      text:
        type: string
      tr:
        items:
          $ref: '#/definitions/domain.ExampleTranslation'
        type: array
    required:
    - text
    type: object
  domain.ExampleTranslation:
    properties:
      text:
        type: string
    required:
    - text
    type: object
  domain.Mean:
    properties:
      text:
        type: string
    required:
    - text
    type: object
  domain.ParagraphAlignNode:
    properties:
      aw:
        items:
          $ref: '#/definitions/domain.WordAlignNode'
        type: array
      op:
        type: string
      tp:
        type: string
    type: object
  domain.Translation:
    properties:
      ex:
        items:
          $ref: '#/definitions/domain.Example'
        type: array
      mean:
        items:
          $ref: '#/definitions/domain.Mean'
        type: array
      pos:
        type: string
      text:
        type: string
    required:
    - text
    type: object
  domain.User:
    properties:
      email:
        type: string
      id:
        type: string
      isAdmin:
        type: boolean
    type: object
  domain.WordAlignNode:
    properties:
      iow:
        items:
          type: integer
        type: array
      itw:
        items:
          type: integer
        type: array
    type: object
  get_book.Output:
    properties:
      book:
        $ref: '#/definitions/domain.Book'
    type: object
  get_books.Output:
    properties:
      books:
        items:
          $ref: '#/definitions/domain.Book'
        type: array
    type: object
  login.Input:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  login.Output:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/domain.User'
    type: object
  logout.Output:
    properties:
      success:
        type: boolean
    type: object
  lookup.Input:
    properties:
      lang:
        type: string
      text:
        type: string
      ui:
        type: string
    required:
    - lang
    - text
    - ui
    type: object
  lookup.Output:
    properties:
      def:
        items:
          $ref: '#/definitions/domain.Definition'
        type: array
      head:
        additionalProperties: {}
        type: object
    required:
    - def
    type: object
  me.Output:
    properties:
      user:
        $ref: '#/definitions/domain.User'
    type: object
  refresh.Input:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  refresh.Output:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  register.Input:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  register.Output:
    properties:
      success:
        type: boolean
    type: object
  translate_book.Output:
    properties:
      book:
        $ref: '#/definitions/domain.Book'
      message:
        type: string
    type: object
  update_book.Output:
    properties:
      book:
        $ref: '#/definitions/domain.Book'
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact: {}
  title: Nim2Book api
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/login.Input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/login.Output'
      summary: Login user
      tags:
      - auth
  /auth/logout:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/logout.Output'
      summary: Logout user
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/refresh.Input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/refresh.Output'
      summary: Refresh user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/register.Input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/register.Output'
      summary: Register user
      tags:
      - auth
  /book:
    get:
      parameters:
      - description: Chapter path
        in: query
        name: author
        type: string
      - description: Chapter path
        in: query
        name: title
        type: string
      - description: Chapter path
        in: query
        name: page
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/get_books.Output'
      summary: Get books
      tags:
      - book
  /book/{id}:
    get:
      parameters:
      - description: Book id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/get_book.Output'
      summary: Get book by id
      tags:
      - book
    put:
      parameters:
      - description: Cover file
        in: formData
        name: cover
        type: file
      - description: Author book
        in: formData
        name: author
        type: string
      - description: Title book
        in: formData
        name: title
        type: string
      - description: Book id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/update_book.Output'
      security:
      - BearerAuth: []
      summary: Update book
      tags:
      - book
  /book/get-chapter/{path}:
    get:
      parameters:
      - description: Chapter path
        in: path
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ChapterAlignNode'
      summary: Get book chapter
      tags:
      - book
  /dictionary/lookup:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/lookup.Input'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lookup.Output'
      summary: Get translate from dictionary
      tags:
      - dictionary
  /file/public:
    get:
      parameters:
      - description: path
        in: query
        name: path
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Get file data
      tags:
      - file
  /translate/book:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Upload file
        in: formData
        name: file
        required: true
        type: file
      - description: Source lang
        in: formData
        name: from
        required: true
        type: string
      - description: Target lang
        in: formData
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/translate_book.Output'
      security:
      - BearerAuth: []
      summary: Translate book
      tags:
      - translate
  /user/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/me.Output'
      security:
      - BearerAuth: []
      summary: Get user info
      tags:
      - user
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
