// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDictionaryRepo creates a new instance of MockDictionaryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDictionaryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDictionaryRepo {
	mock := &MockDictionaryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDictionaryRepo is an autogenerated mock type for the DictionaryRepo type
type MockDictionaryRepo struct {
	mock.Mock
}

type MockDictionaryRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDictionaryRepo) EXPECT() *MockDictionaryRepo_Expecter {
	return &MockDictionaryRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDictionaryRepo
func (_mock *MockDictionaryRepo) Create(ctx context.Context, domainDict *domain.DictionaryWord) (*domain.DictionaryWord, error) {
	ret := _mock.Called(ctx, domainDict)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.DictionaryWord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DictionaryWord) (*domain.DictionaryWord, error)); ok {
		return returnFunc(ctx, domainDict)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DictionaryWord) *domain.DictionaryWord); ok {
		r0 = returnFunc(ctx, domainDict)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DictionaryWord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.DictionaryWord) error); ok {
		r1 = returnFunc(ctx, domainDict)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDictionaryRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDictionaryRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - domainDict *domain.DictionaryWord
func (_e *MockDictionaryRepo_Expecter) Create(ctx interface{}, domainDict interface{}) *MockDictionaryRepo_Create_Call {
	return &MockDictionaryRepo_Create_Call{Call: _e.mock.On("Create", ctx, domainDict)}
}

func (_c *MockDictionaryRepo_Create_Call) Run(run func(ctx context.Context, domainDict *domain.DictionaryWord)) *MockDictionaryRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.DictionaryWord
		if args[1] != nil {
			arg1 = args[1].(*domain.DictionaryWord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDictionaryRepo_Create_Call) Return(dictionaryWord *domain.DictionaryWord, err error) *MockDictionaryRepo_Create_Call {
	_c.Call.Return(dictionaryWord, err)
	return _c
}

func (_c *MockDictionaryRepo_Create_Call) RunAndReturn(run func(ctx context.Context, domainDict *domain.DictionaryWord) (*domain.DictionaryWord, error)) *MockDictionaryRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetDictionaryWordsByText provides a mock function for the type MockDictionaryRepo
func (_mock *MockDictionaryRepo) GetDictionaryWordsByText(ctx context.Context, text string, fromLang string, toLang string) ([]*domain.DictionaryWord, error) {
	ret := _mock.Called(ctx, text, fromLang, toLang)

	if len(ret) == 0 {
		panic("no return value specified for GetDictionaryWordsByText")
	}

	var r0 []*domain.DictionaryWord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*domain.DictionaryWord, error)); ok {
		return returnFunc(ctx, text, fromLang, toLang)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []*domain.DictionaryWord); ok {
		r0 = returnFunc(ctx, text, fromLang, toLang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.DictionaryWord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, text, fromLang, toLang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDictionaryRepo_GetDictionaryWordsByText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDictionaryWordsByText'
type MockDictionaryRepo_GetDictionaryWordsByText_Call struct {
	*mock.Call
}

// GetDictionaryWordsByText is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - fromLang string
//   - toLang string
func (_e *MockDictionaryRepo_Expecter) GetDictionaryWordsByText(ctx interface{}, text interface{}, fromLang interface{}, toLang interface{}) *MockDictionaryRepo_GetDictionaryWordsByText_Call {
	return &MockDictionaryRepo_GetDictionaryWordsByText_Call{Call: _e.mock.On("GetDictionaryWordsByText", ctx, text, fromLang, toLang)}
}

func (_c *MockDictionaryRepo_GetDictionaryWordsByText_Call) Run(run func(ctx context.Context, text string, fromLang string, toLang string)) *MockDictionaryRepo_GetDictionaryWordsByText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDictionaryRepo_GetDictionaryWordsByText_Call) Return(dictionaryWords []*domain.DictionaryWord, err error) *MockDictionaryRepo_GetDictionaryWordsByText_Call {
	_c.Call.Return(dictionaryWords, err)
	return _c
}

func (_c *MockDictionaryRepo_GetDictionaryWordsByText_Call) RunAndReturn(run func(ctx context.Context, text string, fromLang string, toLang string) ([]*domain.DictionaryWord, error)) *MockDictionaryRepo_GetDictionaryWordsByText_Call {
	_c.Call.Return(run)
	return _c
}
