// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRedis creates a new instance of MockRedis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedis {
	mock := &MockRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedis is an autogenerated mock type for the Redis type
type MockRedis struct {
	mock.Mock
}

type MockRedis_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedis) EXPECT() *MockRedis_Expecter {
	return &MockRedis_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRedis
func (_mock *MockRedis) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedis_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRedis_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedis_Expecter) Get(ctx interface{}, key interface{}) *MockRedis_Get_Call {
	return &MockRedis_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockRedis_Get_Call) Run(run func(ctx context.Context, key string)) *MockRedis_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedis_Get_Call) Return(bytes []byte, err error) *MockRedis_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRedis_Get_Call) RunAndReturn(run func(ctx context.Context, key string) ([]byte, error)) *MockRedis_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRedis
func (_mock *MockRedis) Save(ctx context.Context, key string, value []byte, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedis_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRedis_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - expiration time.Duration
func (_e *MockRedis_Expecter) Save(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockRedis_Save_Call {
	return &MockRedis_Save_Call{Call: _e.mock.On("Save", ctx, key, value, expiration)}
}

func (_c *MockRedis_Save_Call) Run(run func(ctx context.Context, key string, value []byte, expiration time.Duration)) *MockRedis_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRedis_Save_Call) Return(err error) *MockRedis_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedis_Save_Call) RunAndReturn(run func(ctx context.Context, key string, value []byte, expiration time.Duration) error) *MockRedis_Save_Call {
	_c.Call.Return(run)
	return _c
}
