// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	"github.com/nimyab/nim2book-back/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenreRepository creates a new instance of MockGenreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenreRepository {
	mock := &MockGenreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenreRepository is an autogenerated mock type for the GenreRepository type
type MockGenreRepository struct {
	mock.Mock
}

type MockGenreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenreRepository) EXPECT() *MockGenreRepository_Expecter {
	return &MockGenreRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockGenreRepository
func (_mock *MockGenreRepository) List(ctx context.Context, opts repository.QueryOptions) ([]*domain.Genre, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Genre
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.QueryOptions) ([]*domain.Genre, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.QueryOptions) []*domain.Genre); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Genre)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.QueryOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenreRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGenreRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts repository.QueryOptions
func (_e *MockGenreRepository_Expecter) List(ctx interface{}, opts interface{}) *MockGenreRepository_List_Call {
	return &MockGenreRepository_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *MockGenreRepository_List_Call) Run(run func(ctx context.Context, opts repository.QueryOptions)) *MockGenreRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.QueryOptions
		if args[1] != nil {
			arg1 = args[1].(repository.QueryOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenreRepository_List_Call) Return(genres []*domain.Genre, err error) *MockGenreRepository_List_Call {
	_c.Call.Return(genres, err)
	return _c
}

func (_c *MockGenreRepository_List_Call) RunAndReturn(run func(ctx context.Context, opts repository.QueryOptions) ([]*domain.Genre, error)) *MockGenreRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
