// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIsVip holds the string denoting the is_vip field in the database.
	FieldIsVip = "is_vip"
	// FieldIsAdmin holds the string denoting the is_admin field in the database.
	FieldIsAdmin = "is_admin"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeGoogleAccount holds the string denoting the google_account edge name in mutations.
	EdgeGoogleAccount = "google_account"
	// EdgeBasicAccount holds the string denoting the basic_account edge name in mutations.
	EdgeBasicAccount = "basic_account"
	// EdgePersonalBooks holds the string denoting the personal_books edge name in mutations.
	EdgePersonalBooks = "personal_books"
	// EdgeFcmTokens holds the string denoting the fcm_tokens edge name in mutations.
	EdgeFcmTokens = "fcm_tokens"
	// Table holds the table name of the user in the database.
	Table = "users"
	// GoogleAccountTable is the table that holds the google_account relation/edge.
	GoogleAccountTable = "google_accounts"
	// GoogleAccountInverseTable is the table name for the GoogleAccount entity.
	// It exists in this package in order to avoid circular dependency with the "googleaccount" package.
	GoogleAccountInverseTable = "google_accounts"
	// GoogleAccountColumn is the table column denoting the google_account relation/edge.
	GoogleAccountColumn = "user_google_account"
	// BasicAccountTable is the table that holds the basic_account relation/edge.
	BasicAccountTable = "basic_accounts"
	// BasicAccountInverseTable is the table name for the BasicAccount entity.
	// It exists in this package in order to avoid circular dependency with the "basicaccount" package.
	BasicAccountInverseTable = "basic_accounts"
	// BasicAccountColumn is the table column denoting the basic_account relation/edge.
	BasicAccountColumn = "user_basic_account"
	// PersonalBooksTable is the table that holds the personal_books relation/edge.
	PersonalBooksTable = "personal_books"
	// PersonalBooksInverseTable is the table name for the PersonalBook entity.
	// It exists in this package in order to avoid circular dependency with the "personalbook" package.
	PersonalBooksInverseTable = "personal_books"
	// PersonalBooksColumn is the table column denoting the personal_books relation/edge.
	PersonalBooksColumn = "user_personal_books"
	// FcmTokensTable is the table that holds the fcm_tokens relation/edge.
	FcmTokensTable = "fcm_tokens"
	// FcmTokensInverseTable is the table name for the FcmToken entity.
	// It exists in this package in order to avoid circular dependency with the "fcmtoken" package.
	FcmTokensInverseTable = "fcm_tokens"
	// FcmTokensColumn is the table column denoting the fcm_tokens relation/edge.
	FcmTokensColumn = "user_fcm_tokens"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldIsVip,
	FieldIsAdmin,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsVip holds the default value on creation for the "is_vip" field.
	DefaultIsVip bool
	// DefaultIsAdmin holds the default value on creation for the "is_admin" field.
	DefaultIsAdmin bool
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIsVip orders the results by the is_vip field.
func ByIsVip(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsVip, opts...).ToFunc()
}

// ByIsAdmin orders the results by the is_admin field.
func ByIsAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAdmin, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByGoogleAccountField orders the results by google_account field.
func ByGoogleAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGoogleAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByBasicAccountField orders the results by basic_account field.
func ByBasicAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBasicAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByPersonalBooksCount orders the results by personal_books count.
func ByPersonalBooksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPersonalBooksStep(), opts...)
	}
}

// ByPersonalBooks orders the results by personal_books terms.
func ByPersonalBooks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPersonalBooksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFcmTokensCount orders the results by fcm_tokens count.
func ByFcmTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFcmTokensStep(), opts...)
	}
}

// ByFcmTokens orders the results by fcm_tokens terms.
func ByFcmTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFcmTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newGoogleAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GoogleAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, GoogleAccountTable, GoogleAccountColumn),
	)
}
func newBasicAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BasicAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, BasicAccountTable, BasicAccountColumn),
	)
}
func newPersonalBooksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PersonalBooksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PersonalBooksTable, PersonalBooksColumn),
	)
}
func newFcmTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FcmTokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FcmTokensTable, FcmTokensColumn),
	)
}
