// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package update_personal_user_book

import (
	"context"

	"github.com/nimyab/nim2book-back/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockS3 creates a new instance of MockS3. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3 {
	mock := &MockS3{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockS3 is an autogenerated mock type for the S3 type
type MockS3 struct {
	mock.Mock
}

type MockS3_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3) EXPECT() *MockS3_Expecter {
	return &MockS3_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function for the type MockS3
func (_mock *MockS3) Upload(path string, data []byte) error {
	ret := _mock.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(path, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockS3_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockS3_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - path string
//   - data []byte
func (_e *MockS3_Expecter) Upload(path interface{}, data interface{}) *MockS3_Upload_Call {
	return &MockS3_Upload_Call{Call: _e.mock.On("Upload", path, data)}
}

func (_c *MockS3_Upload_Call) Run(run func(path string, data []byte)) *MockS3_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockS3_Upload_Call) Return(err error) *MockS3_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockS3_Upload_Call) RunAndReturn(run func(path string, data []byte) error) *MockS3_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPersonalBookRepository creates a new instance of MockPersonalBookRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPersonalBookRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPersonalBookRepository {
	mock := &MockPersonalBookRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPersonalBookRepository is an autogenerated mock type for the PersonalBookRepository type
type MockPersonalBookRepository struct {
	mock.Mock
}

type MockPersonalBookRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPersonalBookRepository) EXPECT() *MockPersonalBookRepository_Expecter {
	return &MockPersonalBookRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) GetByID(ctx context.Context, id domain.ID) (*domain.PersonalBook, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.PersonalBook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) (*domain.PersonalBook, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ID) *domain.PersonalBook); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockPersonalBookRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ID
func (_e *MockPersonalBookRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockPersonalBookRepository_GetByID_Call {
	return &MockPersonalBookRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockPersonalBookRepository_GetByID_Call) Run(run func(ctx context.Context, id domain.ID)) *MockPersonalBookRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ID
		if args[1] != nil {
			arg1 = args[1].(domain.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_GetByID_Call) Return(personalBook *domain.PersonalBook, err error) *MockPersonalBookRepository_GetByID_Call {
	_c.Call.Return(personalBook, err)
	return _c
}

func (_c *MockPersonalBookRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id domain.ID) (*domain.PersonalBook, error)) *MockPersonalBookRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPersonalBookRepository
func (_mock *MockPersonalBookRepository) Update(ctx context.Context, book *domain.PersonalBook) (*domain.PersonalBook, error) {
	ret := _mock.Called(ctx, book)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.PersonalBook
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBook) (*domain.PersonalBook, error)); ok {
		return returnFunc(ctx, book)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.PersonalBook) *domain.PersonalBook); ok {
		r0 = returnFunc(ctx, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PersonalBook)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.PersonalBook) error); ok {
		r1 = returnFunc(ctx, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPersonalBookRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPersonalBookRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - book *domain.PersonalBook
func (_e *MockPersonalBookRepository_Expecter) Update(ctx interface{}, book interface{}) *MockPersonalBookRepository_Update_Call {
	return &MockPersonalBookRepository_Update_Call{Call: _e.mock.On("Update", ctx, book)}
}

func (_c *MockPersonalBookRepository_Update_Call) Run(run func(ctx context.Context, book *domain.PersonalBook)) *MockPersonalBookRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.PersonalBook
		if args[1] != nil {
			arg1 = args[1].(*domain.PersonalBook)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPersonalBookRepository_Update_Call) Return(personalBook *domain.PersonalBook, err error) *MockPersonalBookRepository_Update_Call {
	_c.Call.Return(personalBook, err)
	return _c
}

func (_c *MockPersonalBookRepository_Update_Call) RunAndReturn(run func(ctx context.Context, book *domain.PersonalBook) (*domain.PersonalBook, error)) *MockPersonalBookRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthorRepository creates a new instance of MockAuthorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthorRepository {
	mock := &MockAuthorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthorRepository is an autogenerated mock type for the AuthorRepository type
type MockAuthorRepository struct {
	mock.Mock
}

type MockAuthorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthorRepository) EXPECT() *MockAuthorRepository_Expecter {
	return &MockAuthorRepository_Expecter{mock: &_m.Mock}
}

// GetOrCreate provides a mock function for the type MockAuthorRepository
func (_mock *MockAuthorRepository) GetOrCreate(ctx context.Context, name string) (*domain.Author, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *domain.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Author, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Author); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthorRepository_GetOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreate'
type MockAuthorRepository_GetOrCreate_Call struct {
	*mock.Call
}

// GetOrCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockAuthorRepository_Expecter) GetOrCreate(ctx interface{}, name interface{}) *MockAuthorRepository_GetOrCreate_Call {
	return &MockAuthorRepository_GetOrCreate_Call{Call: _e.mock.On("GetOrCreate", ctx, name)}
}

func (_c *MockAuthorRepository_GetOrCreate_Call) Run(run func(ctx context.Context, name string)) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthorRepository_GetOrCreate_Call) Return(author *domain.Author, err error) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockAuthorRepository_GetOrCreate_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.Author, error)) *MockAuthorRepository_GetOrCreate_Call {
	_c.Call.Return(run)
	return _c
}
