// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Author is the predicate function for author builders.
type Author func(*sql.Selector)

// BasicAccount is the predicate function for basicaccount builders.
type BasicAccount func(*sql.Selector)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// BookChapter is the predicate function for bookchapter builders.
type BookChapter func(*sql.Selector)

// Dictionary is the predicate function for dictionary builders.
type Dictionary func(*sql.Selector)

// DictionaryExample is the predicate function for dictionaryexample builders.
type DictionaryExample func(*sql.Selector)

// FcmToken is the predicate function for fcmtoken builders.
type FcmToken func(*sql.Selector)

// Genre is the predicate function for genre builders.
type Genre func(*sql.Selector)

// GoogleAccount is the predicate function for googleaccount builders.
type GoogleAccount func(*sql.Selector)

// PersonalBook is the predicate function for personalbook builders.
type PersonalBook func(*sql.Selector)

// PersonalBookChapter is the predicate function for personalbookchapter builders.
type PersonalBookChapter func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
